/* ============================================================
 * 量子河洛 · 题库数据
 * 来源：《量子河洛业务培训评测考试体系》2026-09-21
 * 四维能力：产品知识/分析思维/销售表达/方法选择
 * ============================================================ */
window.SYSTEM_DEFS = window.SYSTEM_DEFS || [];
window.SYSTEM_DEFS.push({
  key:'qlhl', name:'量子河洛', short:'量子河洛', icon:'⚛️', color:'#7c3aed',
  sub:'组合创新方法论 + Multi-Agent 研发闭环 + 数据资产化研发中台',
  chapters:['懂产品','会分析','会卖','会选','综合考试'],
  dimensions:['产品知识','分析思维','销售表达','方法选择'],
  exam:{ total:100, duration:120*60, pass:80, title:'结业综合考试（闭卷 · 100 分 · 120 分钟 · 80 分通过）' },
  bank:[
  /* ============ 懂产品 ============ */
  {id:'q1',chapter:'懂产品',section:'L1 基础层',type:'single',dimension:'产品知识',difficulty:1,
   q:'量子河洛在市场中的定位是？',
   options:['自己生产中药饮片卖给药店','中立第三方"卖铲人"——产业级 AI 创新研发中台','保健食品代工厂','医药电商渠道商'],
   answer:['B'], explain:'量子河洛是"组合创新方法论 + Multi-Agent 研发闭环 + 数据资产化"一体化的产业级研发中台，不卖药、不和客户抢市场。'},
  {id:'q2',chapter:'懂产品',section:'L1 基础层',type:'single',dimension:'产品知识',difficulty:1,
   q:'下列哪一项不属于量子河洛的五大模块？',
   options:['市场洞察雷达','AI 智能组方·组合创新','物流仓储配送','数据资产化'],
   answer:['C'], explain:'五大模块：市场洞察雷达 / AI 智能组方·组合创新 / 合规预检 / 实验工艺验证 / 数据资产化。'},
  {id:'q3',chapter:'懂产品',section:'L1 基础层',type:'single',dimension:'产品知识',difficulty:1,
   q:'"更准"价值的正确表述是？',
   options:['研发周期压缩 30-80%','AI 组方可追溯、可解释、可审计','中型企业首年 180-265 万','合规预检前置'],
   answer:['B'], explain:'更快=周期压缩30-80%；更准=可追溯可解释可审计；更省=中型首年180-265万、6-18月回本；更稳=合规预检前置。'},
  {id:'q4',chapter:'懂产品',section:'L1 基础层',type:'judge',dimension:'产品知识',difficulty:1,
   q:'说明书修订产品线对应的政策大限是 2030 年，涉及 4 万+ 批文待修订，市场规模约 200-800 亿。',
   options:['对','错'], answer:['对'],
   explain:'三者均为说明书修订产品线核心事实。'},
  {id:'q5',chapter:'懂产品',section:'L1 基础层',type:'judge',dimension:'产品知识',difficulty:1,
   q:'量子河洛的等保 2.0 测评备案已经完成，营销人员可以向客户承诺具体安全指标。',
   options:['对','错'], answer:['错'],
   explain:'等保 2.0 定级建议为第三级，但测评备案尚未完成。核心纪律是"区分能力 vs 承诺，不得自行承诺安全指标"。'},
  {id:'q6',chapter:'懂产品',section:'L1 基础层',type:'fill',dimension:'产品知识',difficulty:1,
   q:'组织内六角色包括：研发总监、配方工程师、品牌市场、产品运营、注册专员和____。',
   answer:'CFO（首席财务官/财务负责人）', keywords:['CFO','财务'], explain:'CFO 关注投产比与回本周期，是"更省"价值的主要沟通对象。'},
  {id:'q7',chapter:'懂产品',section:'L2 应用层',type:'single',dimension:'产品知识',difficulty:2,
   q:'某中药饮片企业负责人第一次见面问"你们自己是不是也做药？会不会跟我们抢生意？"最符合定位的回应是：',
   options:['"我们也有几个自研产品，可以合作"','"我们是中立第三方卖铲人，只做研发中台帮您研发，不卖药、不和您抢市场，数据资产也归您"','"这个看情况"','"我们主要做渠道"'],
   answer:['B'], explain:'B 准确传达中立第三方定位，并以"数据资产归您"强化信任。'},
  {id:'q8',chapter:'懂产品',section:'L2 应用层',type:'subjective',dimension:'产品知识',difficulty:2,
   q:'客户问"你们的 AI 组方是不是黑箱？我不放心。"请用"更准"价值作答（不少于 3 个要点）。',
   rubric:'① AI 组方不是黑箱——强调可追溯、可解释、可审计；② 医理底座是君臣佐使/七情合和/十八反十九畏，经三层约束规则引擎落地；③ 有 12 个专业智能体分工 + AI 防错中间件四层防线，每个决策有据可查。'},
  {id:'q9',chapter:'懂产品',section:'L2 应用层',type:'single',dimension:'产品知识',difficulty:2,
   q:'某保健食品企业负责人问"你们大概要花多少钱？"最恰当的做法是：',
   options:['直接承诺"6 个月一定回本"','报出三档定价，并说明分利机制与投产比口径目前待确认、不能口头承诺回本数字','说"很便宜"','把竞品价格报给对方'],
   answer:['B'], explain:'三档定价（大型520-730万/中型180-265万/小型20-33万）+四部署；分利机制、投产比口径待确认，如实报档位+标待确认项、不承诺。'},
  {id:'q10',chapter:'懂产品',section:'L3 综合层',type:'subjective',dimension:'产品知识',difficulty:3,
   q:'案例：中型中药饮片企业，研发周期长、组方靠老师傅经验、担心踩功效宣称红线、想把经验沉淀成数据资产。请以"四价值"为骨架写 3 分钟产品价值陈述（每条落到客户利益收尾）。',
   rubric:'更快=周期压缩30-80%（法定审批除外）抢窗口；更准=可追溯可解释可审计，经验变系统规则资产；更省=中型首年180-265万、6-18月回本（投产比以书面方案确认，不口头承诺）；更稳=合规预检前置规避红线。收尾"又快又稳上新、经验变资产"。'},

  /* ============ 会分析 ============ */
  {id:'q11',chapter:'会分析',section:'L1 基础层',type:'single',dimension:'分析思维',difficulty:1,
   q:'STP 三个字母分别代表？',
   options:['细分、定位、促销','市场细分、目标市场选择、市场定位','产品、价格、渠道','情境、任务、人'],
   answer:['B'], explain:'STP = Segmentation(细分)/Targeting(目标市场选择)/Positioning(定位)。'},
  {id:'q12',chapter:'会分析',section:'L1 基础层',type:'single',dimension:'分析思维',difficulty:1,
   q:'关于 4P，下列说法正确的是？',
   options:['各自独立、互不影响','产品、价格、渠道、推广四者必须匹配','价格最重要','推广最重要'],
   answer:['B'], explain:'4P 的核心纪律是四者匹配一致，否则定位错乱、资源浪费。'},
  {id:'q13',chapter:'会分析',section:'L1 基础层',type:'single',dimension:'分析思维',difficulty:1,
   q:'金字塔原理的四项核心原则不包括？',
   options:['结论先行','以上统下','归类分组 MECE','数据越多越好'],
   answer:['D'], explain:'金字塔原理 = 结论先行、以上统下、归类分组(MECE)、逻辑递进。'},
  {id:'q14',chapter:'会分析',section:'L1 基础层',type:'judge',dimension:'分析思维',difficulty:1,
   q:'SWOT 中，S（优势）和 W（劣势）是外部因素，O（机会）和 T（威胁）是内部因素。',
   options:['对','错'], answer:['错'],
   explain:'S/W 是内部因素，O/T 是外部因素，题目说反了。'},
  {id:'q15',chapter:'会分析',section:'L1 基础层',type:'judge',dimension:'分析思维',difficulty:1,
   q:'3W 黄金圈的正确表达顺序是 Why→How→What，由内向外。',
   options:['对','错'], answer:['对'],
   explain:'黄金圈由内向外：先讲为什么(Why)，再讲怎么做(How)，最后讲是什么(What)。'},
  {id:'q16',chapter:'会分析',section:'L1 基础层',type:'fill',dimension:'分析思维',difficulty:1,
   q:'卡诺模型中，做不好会被淘汰的是____型需求；能形成差异化、给客户惊喜的是____型需求。',
   answer:'基本型；兴奋型', keywords:['基本','兴奋'], explain:'基本型做不好被淘汰；兴奋型是差异化来源；期望型"越多越好"；无差异型无所谓；反向型做了招反感。'},
  {id:'q17',chapter:'会分析',section:'L2 应用层',type:'single',dimension:'分析思维',difficulty:2,
   q:'用卡诺模型看量子河洛的"合规预检"对研发生产型企业而言，最可能属于哪一类需求？',
   options:['兴奋型','无差异型','基本型','反向型'],
   answer:['C'], explain:'对研发生产型企业，合规是底线（踩红线被罚/下架），做不好会被淘汰，属基本型——应作为"必备能力"陈述。'},
  {id:'q18',chapter:'会分析',section:'L2 应用层',type:'subjective',dimension:'分析思维',difficulty:2,
   q:'请用 3W 黄金圈为量子河洛写一个 30 秒开场白，要求从 Why 讲起。',
   rubric:'Why=中医药大健康行业研发慢、靠经验、合规风险高；How=组合创新方法论+Multi-Agent研发闭环+数据资产化解题；What=中立第三方产业级AI创新研发中台，帮您又快又稳做产品。'},
  {id:'q19',chapter:'会分析',section:'L2 应用层',type:'single',dimension:'分析思维',difficulty:2,
   q:'某团队做完 SWOT 后，决定"用自己的强项去抓行业机会"，这属于哪种策略？',
   options:['WO 策略','ST 策略','WT 策略','SO 策略'],
   answer:['D'], explain:'SO=优势+机会(进攻)；WO=劣势+机会(补齐)；ST=优势+威胁(防御)；WT=劣势+威胁(收缩)。'},
  {id:'q20',chapter:'会分析',section:'L3 综合层',type:'subjective',dimension:'分析思维',difficulty:3,
   q:'案例：以 STP + SWOT 为框架，为量子河洛在"药食同源消费品"目标市场写一页纸市场打法方案（含目标客户画像、定位一句话、机会与威胁各一条、一个行动策略）。',
   rubric:'STP：目标市场=有新品计划、具备资质、追求差异化的中型药食同源企业；定位=中立第三方研发中台"更快更稳上新"。SWOT：S=组合创新+可追溯；W=品牌认知度低；O=药食同源走热+2030政策窗口；T=竞品低价。行动(SO)=主打"更快上新+合规前置"组合包。'},

  /* ============ 会卖 ============ */
  {id:'q21',chapter:'会卖',section:'L1 基础层',type:'single',dimension:'销售表达',difficulty:1,
   q:'FABE 中 F、A、B、E 分别指？',
   options:['特征、优点、利益、证据','功能、分析、品牌、体验','需求、方案、价值、承诺','事实、态度、行为、评估'],
   answer:['A'], explain:'FABE = Feature(特征)/Advantage(优点)/Benefit(利益)/Evidence(证据)。'},
  {id:'q22',chapter:'会卖',section:'L1 基础层',type:'single',dimension:'销售表达',difficulty:1,
   q:'SPIN 中四类提问的正确顺序是？',
   options:['情境→问题→暗示→需求-效益','问题→情境→效益→暗示','需求→问题→情境→方案','情境→效益→问题→暗示'],
   answer:['A'], explain:'SPIN = Situation/Problem/Implication/Need-payoff，由浅入深显性化需求。'},
  {id:'q23',chapter:'会卖',section:'L1 基础层',type:'single',dimension:'销售表达',difficulty:1,
   q:'MEDDIC 中，M 和 E 分别代表？',
   options:['Market 和 Estimate','Metrics（可量化指标）和 Economic buyer（经济决策人）','Money 和 End user','Method 和 Evaluation'],
   answer:['B'], explain:'MEDDIC = Metrics/Economic buyer/Decision criteria/Decision process/Identify pain/Champion。'},
  {id:'q24',chapter:'会卖',section:'L1 基础层',type:'judge',dimension:'销售表达',difficulty:1,
   q:'AIDA 的正确顺序是 注意(A)→兴趣(I)→欲望(D)→行动(A)。',
   options:['对','错'], answer:['对'],
   explain:'AIDA = Attention/Interest/Desire/Action。'},
  {id:'q25',chapter:'会卖',section:'L1 基础层',type:'judge',dimension:'销售表达',difficulty:1,
   q:'挑战式销售的核心动作是 Teach（教导）、Tailor（定制）、Take Control（掌控对话）。',
   options:['对','错'], answer:['对'],
   explain:'挑战式销售以"教导、定制、掌控"为核心，交付颠覆认知的商业洞察。'},
  {id:'q26',chapter:'会卖',section:'L1 基础层',type:'fill',dimension:'销售表达',difficulty:1,
   q:'RAIN 中，R 指____（建立信任），A 指 Aspirations & Afflictions（期望与痛点）。',
   answer:'Rapport（融洽/信任关系）', keywords:['rapport','融洽','信任'], explain:'RAIN = Rapport/Aspirations&Afflictions/Impact/New Reality。'},
  {id:'q27',chapter:'会卖',section:'L2 应用层',type:'single',dimension:'销售表达',difficulty:2,
   q:'第一次拜访中药饮片企业，对方研发负责人说"我们研发还行，没啥大问题"。此时最应该做的是？',
   options:['立刻上 FABE 讲我们多厉害','用 SPIN 提问摸底，先找对方的隐性问题和痛点','直接报价','留下资料就走'],
   answer:['B'], explain:'客户还没意识到问题（隐性需求），应先用 SPIN 把痛点显性化；直接 FABE 是常见误用。'},
  {id:'q28',chapter:'会卖',section:'L2 应用层',type:'subjective',dimension:'销售表达',difficulty:2,
   q:'用 FABE 为"市场洞察雷达"写一段话术，要求落到客户利益并给出证据。',
   rubric:'F=自动扫描市场趋势/法规动态/竞品/文献；A=7×24自动监测不用人工盯；B=先人一步发现新机会、提前避开政策红线；E=现场做一次目标品类扫描 Demo。'},
  {id:'q29',chapter:'会卖',section:'L2 应用层',type:'single',dimension:'销售表达',difficulty:2,
   q:'一位技术型客户（研发总监）反复说"你拿数据/证据说话，别跟我讲概念"。最适合的方法组合是？',
   options:['桑德勒相互设限 + 顾问式诊断','FABE（重点用 E 证据）+ 挑战式，强调可追溯/可解释/可审计','AIDA 情感打动','只讲情怀'],
   answer:['B'], explain:'技术型客户要证据，FABE 的 E 与"可追溯可解释可审计"对口；挑战式能提供新视角。'},
  {id:'q30',chapter:'会卖',section:'L3 综合层',type:'subjective',dimension:'销售表达',difficulty:3,
   q:'案例：保健食品企业采购负责人说"你们太贵了，别家报价只有你们一半"。请用桑德勒销售法 + FABE 写一段回应话术（不轻易让步、拉回价值、落到客户利益）。',
   rubric:'先设限划清"价格"与"价值"边界（"您要便宜方案，还是能更快上市、不出合规问题的方案？"）；做平等关系；用B利益+E风险回拉（周期压缩30-80%、合规前置，返工/罚款远超差价）；收口"把采购指标定清楚再给方案"；不承诺具体数字。'},

  /* ============ 会选 ============ */
  {id:'q31',chapter:'会选',section:'L1 基础层',type:'single',dimension:'方法选择',difficulty:1,
   q:'9 阶段中，"需求诊断"阶段应优先使用的方法是？',
   options:['FABE 直接陈述','SPIN 提问摸底','AARRR','AIDA'],
   answer:['B'], explain:'需求诊断阶段先摸需求，SPIN 由浅入深；直接上 FABE 是常见误用。'},
  {id:'q32',chapter:'会选',section:'L1 基础层',type:'single',dimension:'方法选择',difficulty:1,
   q:'"商机评估"阶段的核心方法是？',
   options:['AIDA','3W 黄金圈','MEDDIC 六维评估','卡诺模型'],
   answer:['C'], explain:'MEDDIC 用于商机资格评估（指标/经济决策人/决策标准/决策流程/痛点/内线）。'},
  {id:'q33',chapter:'会选',section:'L1 基础层',type:'judge',dimension:'方法选择',difficulty:1,
   q:'面对"采购法务"角色，应重点讲技术架构和研发细节。',
   options:['对','错'], answer:['错'],
   explain:'采购法务关注合规、流程、风险与条款；技术细节讲给技术评估者。'},
  {id:'q34',chapter:'会选',section:'L1 基础层',type:'judge',dimension:'方法选择',difficulty:1,
   q:'"见客户就上 FABE"是正确打法。',
   options:['对','错'], answer:['错'],
   explain:'应先 SPIN 摸底需求，否则 FABE 的"利益"对不上号，容易自说自话。'},
  {id:'q35',chapter:'会选',section:'L1 基础层',type:'fill',dimension:'方法选择',difficulty:1,
   q:'签约后对老客户的深化经营，应使用____模型。',
   answer:'AARRR', keywords:['aarrr'], explain:'AARRR = 获取/激活/留存/收入/推荐，适用于已签约客户经营。'},
  {id:'q36',chapter:'会选',section:'L1 基础层',type:'single',dimension:'方法选择',difficulty:1,
   q:'面对"技术评估者"，沟通重点应是？',
   options:['情感与情怀','可追溯、可解释、可审计 + 证据','只讲回本周期','只讲品牌故事'],
   answer:['B'], explain:'技术评估者要证据和机理，讲可追溯/可解释/可审计最对口。'},
  {id:'q37',chapter:'会选',section:'L2 应用层',type:'single',dimension:'方法选择',difficulty:2,
   q:'第一次见客户，对方是"采购合规部门"，最恰当的做法是？',
   options:['立刻演示全部功能','用顾问式 + SPIN，先了解对方采购流程、合规标准与决策流程','直接报最低价','只发产品手册'],
   answer:['B'], explain:'采购合规关注流程与标准，先诊断再方案。'},
  {id:'q38',chapter:'会选',section:'L2 应用层',type:'subjective',dimension:'方法选择',difficulty:2,
   q:'为什么"见客户就上 FABE"属于误用？正确的顺序应该是什么？',
   rubric:'FABE 的 B（利益）必须基于客户真实需求才有杀伤力；没摸清需求就 FABE 会"自说自话"。正确顺序：先用 SPIN 摸底需求→再用 FABE 落到客户利益→关键决策点用 MEDDIC 评估商机。'},
  {id:'q39',chapter:'会选',section:'L2 应用层',type:'single',dimension:'方法选择',difficulty:2,
   q:'竞品对比环节，客户说"别家功能差不多还更便宜"。此时最佳方法组合是？',
   options:['桑德勒相互设限（不盲目降价）+ FABE 证据（差异化价值）+ 挑战式（提供新视角）','立刻降价跟进','贬低竞品','放弃'],
   answer:['A'], explain:'用相互设限守住价格边界，用证据讲差异化，用挑战式给客户没想到的价值视角。'},
  {id:'q40',chapter:'会选',section:'L3 综合层',type:'subjective',dimension:'方法选择',difficulty:3,
   q:'案例：中型研发生产型企业客户，参会人有技术型研发总监、业务型品牌市场负责人、高层 CFO。请设计"分角色方法选择 + 沟通要点"方案。',
   rubric:'研发总监(技术评估者)用 FABE(E证据)+顾问式，讲可追溯可解释可审计；品牌市场(业务型)用 NFABE+AIDA，讲市场洞察雷达找新品类、更快上新；CFO(经济决策人)用 3W黄金圈+MEDDIC，讲"更省"（投产比口径待确认、书面为准不承诺）。'},

  /* ============ 综合考试 ============ */
  {id:'qe1',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'产品知识',difficulty:1,score:3,
   q:'量子河洛的定位是？',
   options:['中药生产商','中立第三方产业级 AI 创新研发中台','医药电商','代工厂'],
   answer:['B'], explain:'中立第三方产业级 AI 创新研发中台。'},
  {id:'qe2',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'产品知识',difficulty:1,score:3,
   q:'五大模块不包括？',
   options:['市场洞察雷达','AI 智能组方·组合创新','合规预检','物流配送'],
   answer:['D'], explain:'五大模块：市场洞察雷达/AI智能组方/合规预检/实验工艺验证/数据资产化。'},
  {id:'qe3',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'产品知识',difficulty:1,score:3,
   q:'"更准"指？',
   options:['周期压缩 30-80%','可追溯可解释可审计','首年 180-265 万','合规预检前置'],
   answer:['B'], explain:'更准=可追溯可解释可审计。'},
  {id:'qe4',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'产品知识',difficulty:1,score:3,
   q:'说明书修订政策大限是？',
   options:['2025','2028','2030','2035'],
   answer:['C'], explain:'说明书修订政策大限为 2030 年。'},
  {id:'qe5',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'分析思维',difficulty:1,score:3,
   q:'STP 指？',
   options:['产品/价格/渠道/推广','细分/目标/定位','情境/任务/人','优势/劣势/机会/威胁'],
   answer:['B'], explain:'STP = 细分/目标/定位。'},
  {id:'qe6',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'分析思维',difficulty:1,score:3,
   q:'金字塔原理四原则不含？',
   options:['结论先行','以上统下','MECE','越多越好'],
   answer:['D'], explain:'金字塔原理不含"越多越好"。'},
  {id:'qe7',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'销售表达',difficulty:1,score:3,
   q:'FABE 的 B 指？',
   options:['特征','优点','利益','证据'],
   answer:['C'], explain:'B = Benefit 利益。'},
  {id:'qe8',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'销售表达',difficulty:1,score:3,
   q:'MEDDIC 的 M 指？',
   options:['市场','指标（Metrics）','渠道','情绪'],
   answer:['B'], explain:'M = Metrics 指标。'},
  {id:'qe9',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'方法选择',difficulty:1,score:3,
   q:'"需求诊断"阶段优先用？',
   options:['FABE','SPIN','AARRR','AIDA'],
   answer:['B'], explain:'需求诊断阶段优先用 SPIN。'},
  {id:'qe10',chapter:'综合考试',section:'综合考试卷',type:'single',dimension:'方法选择',difficulty:1,score:3,
   q:'签约后老客户经营用？',
   options:['STP','MEDDIC','AARRR','SWOT'],
   answer:['C'], explain:'签约后经营用 AARRR。'},
  {id:'qe11',chapter:'综合考试',section:'综合考试卷',type:'multi',dimension:'产品知识',difficulty:1,score:4,
   q:'下列属于量子河洛"四价值"的有？',
   options:['更快','更准','更省','更稳','更贵'],
   answer:['A','B','C','D'], explain:'四价值：更快/更准/更省/更稳。'},
  {id:'qe12',chapter:'综合考试',section:'综合考试卷',type:'multi',dimension:'产品知识',difficulty:1,score:4,
   q:'组织内六角色包括？',
   options:['研发总监','配方工程师','注册专员','CFO','快递员'],
   answer:['A','B','C','D'], explain:'六角色：研发总监/配方工程师/品牌市场/产品运营/注册专员/CFO。'},
  {id:'qe13',chapter:'综合考试',section:'综合考试卷',type:'multi',dimension:'分析思维',difficulty:1,score:4,
   q:'下列属于"会分析"6 模型的有？',
   options:['STP','4P','金字塔原理','SPIN','卡诺模型'],
   answer:['A','B','C','E'], explain:'SPIN 属"会卖"，其余属"会分析"6 模型。'},
  {id:'qe14',chapter:'综合考试',section:'综合考试卷',type:'multi',dimension:'销售表达',difficulty:1,score:4,
   q:'价值陈述家族包括？',
   options:['FABE','NFABE','PFABNE','SCQA','SWOT'],
   answer:['A','B','C','D'], explain:'SWOT 属"会分析"，不属于价值陈述家族。'},
  {id:'qe15',chapter:'综合考试',section:'综合考试卷',type:'multi',dimension:'方法选择',difficulty:1,score:4,
   q:'下列属于"常见误用纠正"的有？',
   options:['见客户就上 FABE→应先 SPIN 摸底','只讲功能不讲利益→应落到客户利益','对高层只讲技术细节→应讲业务价值/ROI','对技术型客户只讲情怀→应给证据','以上都对'],
   answer:['A','B','C','D'], explain:'E 是干扰项。'},
  {id:'qe16',chapter:'综合考试',section:'综合考试卷',type:'subjective',dimension:'销售表达',difficulty:3,score:10,
   q:'情景：中药饮片企业研发总监抱怨"组方靠老师傅，人走了就断档"，请用 FABE 写一段话术（落到客户利益）。',
   rubric:'F=AI组方+规则引擎；A=把经验转成系统规则；B=知识资产化、人走不断档、可追溯可审计；E=现场演示录入老师傅组方逻辑、生成可解释组方。（每要素2分，落到利益2分）'},
  {id:'qe17',chapter:'综合考试',section:'综合考试卷',type:'subjective',dimension:'方法选择',difficulty:3,score:10,
   q:'情景：第一次见"采购合规部门"客户，你该怎么选方法和开场？',
   rubric:'顾问式+SPIN，先问对方采购流程/合规标准/决策流程（4分），不急于推功能（2分），再根据回答匹配方案（4分）。'},
  {id:'qe18',chapter:'综合考试',section:'综合考试卷',type:'subjective',dimension:'分析思维',difficulty:3,score:10,
   q:'情景：用卡诺模型分析，对研发生产型企业，"合规预检"和"市场洞察雷达"分别属于哪类需求？如何影响销售说法？',
   rubric:'合规预检=基本型（必备能力，不能过度当差异化卖点）（5分）；市场洞察雷达=兴奋型/期望型（差异化惊喜，可当亮点）（5分）。'},
  {id:'qe19',chapter:'综合考试',section:'综合考试卷',type:'subjective',dimension:'产品知识',difficulty:3,score:10,
   q:'简答：客户问"AI 组方是不是黑箱"和"你们是不是也卖药"，请分别作答，并说明涉及"待确认"信息时如何表述。',
   rubric:'黑箱→可追溯可解释可审计+规则约束+防错（4分）；是否卖药→中立第三方卖铲人、不抢市场、数据资产归客户（3分）；待确认项（分利/投产比/等保备案）→如实说明、不口头承诺（3分）。'},
  {id:'qe20',chapter:'综合考试',section:'综合考试卷',type:'subjective',dimension:'方法选择',difficulty:3,score:10,
   q:'简答：简述"分角色方法选择"——对技术评估者、经济决策人、采购法务分别用什么方法、讲什么重点？',
   rubric:'技术评估者→FABE(E证据)+顾问式，讲可追溯可解释可审计（4分）；经济决策人→3W黄金圈+MEDDIC，讲ROI/更省，注明待确认不承诺（3分）；采购法务→顾问式+SPIN，讲合规/数据安全/交付流程（3分）。'}
  ]
});
