/* ============================================================
 * CosmoFreq（宇宙频率）· 题库数据
 * 来源：《CosmoFreq营销培训-课程评测与考试题库（含倾向能力测评）》V1.0
 * 四维能力：产品知识/分析能力/销售技能/方法判断
 * ============================================================ */
window.SYSTEM_DEFS = window.SYSTEM_DEFS || [];
window.SYSTEM_DEFS.push({
  key:'cmf', name:'CosmoFreq', short:'CosmoFreq', icon:'🪐', color:'#0ea5e9',
  sub:'机构级科技创新与科技转化全生命周期智能平台',
  chapters:['懂产品','会分析','会卖','会选','综合考试'],
  dimensions:['产品知识','分析能力','销售技能','方法判断'],
  exam:{ total:100, duration:120*60, pass:70, title:'综合考试（闭卷 · 100 分 · 120 分钟 · 70 分通过）' },
  bank:[
  /* ============ 第一阶 · 懂产品 ============ */
  {id:'c1',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'CosmoFreq 的产品定位是？',
   options:['医疗影像 AI 诊断系统','机构级科技创新与科技转化全生命周期智能平台','通用企业办公协同软件','专利检索数据库'],
   answer:['B'], explain:'定位是机构级科技创新与科技转化全生命周期智能平台。'},
  {id:'c2',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'下列不属于"P0 四件套"的是？',
   options:['招投标主线','知识产权','职称评审','课题研究'],
   answer:['C'], explain:'P0 四件套为招投标、知识产权、课题研究、医疗合规；职称评审属 P1/P2。'},
  {id:'c3',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'"对外提交、数据出域"在三级授权中属于？',
   options:['低风险（自动放行）','中风险（人工审核）','高风险（多级签批）','无需授权'],
   answer:['C'], explain:'数据出域/对外提交属高风险，需多级签批。'},
  {id:'c4',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'CosmoFreq 用于数字签名与身份鉴别的国密算法是？',
   options:['SM2','SM3','SM4','MD5'],
   answer:['A'], explain:'SM2 用于签名/鉴别，SM3 杂凑，SM4 对称加密。'},
  {id:'c5',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'借助 AI，标书编制时间能从多少压缩到多少？',
   options:['8 小时→4 小时','3 小时→30 分钟','1 天→半天','30 分钟→5 分钟'],
   answer:['B'], explain:'标书编制 3 小时→30 分钟，提效 83%。'},
  {id:'c6',chapter:'懂产品',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,
   q:'CosmoFreq 已取得等保三级与密评第三方测评报告。',
   options:['对','错'], answer:['对'],
   explain:'已取得等保三级与密评第三方测评报告。'},
  {id:'c7',chapter:'懂产品',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,
   q:'三级模型路由中，约 90% 查询走旗舰模型以保证质量。',
   options:['对','错'], answer:['错'],
   explain:'90% 走轻量模型、10% 走旗舰模型，为降本。'},
  {id:'c8',chapter:'懂产品',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,
   q:'卡诺模型属于"会分析"模块的六个工具之一。',
   options:['对','错'], answer:['对'],
   explain:'卡诺模型属"会分析"模块六工具之一。'},
  {id:'c9',chapter:'懂产品',section:'填空',type:'fill',dimension:'产品知识',difficulty:1,
   q:'CosmoFreq 覆盖 ____ 大业务域（填阿拉伯数字）。',
   answer:'9', keywords:['9'], explain:'九大业务域。'},
  {id:'c10',chapter:'懂产品',section:'填空',type:'fill',dimension:'产品知识',difficulty:1,
   q:'数据按 L1 至 L____ 分五级管理（填数字）。',
   answer:'5', keywords:['5','L5'], explain:'数据分 L1–L5 五级。'},

  /* ============ 第二阶 · 会分析 ============ */
  {id:'c11',chapter:'会分析',section:'单选',type:'single',dimension:'分析能力',difficulty:1,
   q:'STP 理论中，T（Targeting）代表？',
   options:['市场细分','目标市场选择','市场定位','促销'],
   answer:['B'], explain:'T = Targeting 目标市场选择。'},
  {id:'c12',chapter:'会分析',section:'单选',type:'single',dimension:'分析能力',difficulty:1,
   q:'金字塔原理的第一原则是？',
   options:['以上统下','归类分组','结论先行','逻辑递进'],
   answer:['C'], explain:'结论先行是第一原则。'},
  {id:'c13',chapter:'会分析',section:'单选',type:'single',dimension:'分析能力',difficulty:1,
   q:'SWOT 中，S（优势）与 W（劣势）属于？',
   options:['内部因素','外部因素','未来因素','竞争因素'],
   answer:['A'], explain:'S/W 是内部因素，O/T 是外部因素。'},
  {id:'c14',chapter:'会分析',section:'单选',type:'single',dimension:'分析能力',difficulty:1,
   q:'黄金圈法则正确的表达顺序（由内向外）是？',
   options:['What→How→Why','Why→How→What','How→Why→What','What→Why→How'],
   answer:['B'], explain:'黄金圈由内向外：Why→How→What。'},
  {id:'c15',chapter:'会分析',section:'单选',type:'single',dimension:'分析能力',difficulty:1,
   q:'卡诺模型中"做好不加分、做不好淘汰"的是？',
   options:['兴奋型','期望型','基本型','反向型'],
   answer:['C'], explain:'基本型"做好不加分、做不好淘汰"。'},
  {id:'c16',chapter:'会分析',section:'判断',type:'judge',dimension:'分析能力',difficulty:1,
   q:'4P 四要素可以单点发力，不必互相配套。',
   options:['对','错'], answer:['错'],
   explain:'四个 P 必须互相配套。'},
  {id:'c17',chapter:'会分析',section:'判断',type:'judge',dimension:'分析能力',difficulty:1,
   q:'SWOT 分析只需填满四个格子，不必得出行动结论。',
   options:['对','错'], answer:['错'],
   explain:'SWOT 必须得出行动结论。'},
  {id:'c18',chapter:'会分析',section:'判断',type:'judge',dimension:'分析能力',difficulty:1,
   q:'卡诺模型的"兴奋型需求"会随时间迁移为"基本型需求"。',
   options:['对','错'], answer:['对'],
   explain:'兴奋型会随时间迁移为基本型。'},
  {id:'c19',chapter:'会分析',section:'填空',type:'fill',dimension:'分析能力',difficulty:1,
   q:'卡诺模型五类需求为——基本型、期望型、兴奋型、____、____。',
   answer:'无差异型、反向型', keywords:['无差异','反向'], explain:'五类需求：基本型/期望型/兴奋型/无差异型/反向型。'},
  {id:'c20',chapter:'会分析',section:'填空',type:'fill',dimension:'分析能力',difficulty:1,
   q:'用一句话写出 CosmoFreq 的市场定位（P）：____。',
   answer:'机构级科技创新与科技转化全生命周期智能平台', keywords:['科技创新','科技转化','全生命周期','智能平台'], explain:'定位一句话：机构级科技创新与科技转化全生命周期智能平台。'},

  /* ============ 第三阶 · 会卖 ============ */
  {id:'c21',chapter:'会卖',section:'单选',type:'single',dimension:'销售技能',difficulty:1,
   q:'FABE 中，B 代表？',
   options:['特征（Feature）','优点（Advantage）','利益（Benefit）','证据（Evidence）'],
   answer:['C'], explain:'B = Benefit 利益，须落到客户。'},
  {id:'c22',chapter:'会卖',section:'单选',type:'single',dimension:'销售技能',difficulty:1,
   q:'SPIN 中，最能创造紧迫感、让客户意识到代价的是？',
   options:['情景问题','问题问题','暗示问题','需求-回报问题'],
   answer:['C'], explain:'暗示问题让客户自己意识到代价。'},
  {id:'c23',chapter:'会卖',section:'单选',type:'single',dimension:'销售技能',difficulty:1,
   q:'MEDDIC 中，代表"内线支持者"的是？',
   options:['Metrics','Economic Buyer','Champion','Identify Pain'],
   answer:['C'], explain:'Champion = 内线支持者。'},
  {id:'c24',chapter:'会卖',section:'单选',type:'single',dimension:'销售技能',difficulty:1,
   q:'SCQA 框架中，Q 代表？',
   options:['情境','冲突','问题','答案'],
   answer:['C'], explain:'Q = Question 问题。'},
  {id:'c25',chapter:'会卖',section:'单选',type:'single',dimension:'销售技能',difficulty:1,
   q:'挑战式销售的三个核心动作是？',
   options:['教导、定制、掌控','诊断、建议、跟进','关系、痛点、影响','特征、优点、利益'],
   answer:['A'], explain:'三动作：教导 Teach、定制 Tailor、掌控 Take Control。'},
  {id:'c26',chapter:'会卖',section:'判断',type:'judge',dimension:'销售技能',difficulty:1,
   q:'见客户应当直接上 FABE 讲卖点，效率最高。',
   options:['对','错'], answer:['错'],
   explain:'应先 SPIN 摸底再讲价值。'},
  {id:'c27',chapter:'会卖',section:'判断',type:'judge',dimension:'销售技能',difficulty:1,
   q:'MEDDIC 是用于开场陈述的销售话术。',
   options:['对','错'], answer:['错'],
   explain:'MEDDIC 是资格评估工具，非话术。'},
  {id:'c28',chapter:'会卖',section:'判断',type:'judge',dimension:'销售技能',difficulty:1,
   q:'桑德勒销售法强调"前期约定（upfront contract）"。',
   options:['对','错'], answer:['对'],
   explain:'前期约定是桑德勒核心。'},
  {id:'c29',chapter:'会卖',section:'情景',type:'single',dimension:'销售技能',difficulty:2,
   q:'面对技术型的信息科主任，最合适的价值陈述方式是？',
   options:['3W 黄金圈讲愿景','NFABE（数据证据收尾）','NFABI（现场体验冲击）','AARRR 讲增长'],
   answer:['B'], explain:'技术型客户重证据，用 NFABE 数据收尾。'},
  {id:'c30',chapter:'会卖',section:'情景',type:'single',dimension:'销售技能',difficulty:2,
   q:'客户有"成果转化率低"的痛点、但需求尚不明确，第一步应？',
   options:['用 MEDDIC 打分','用 SPIN 挖掘需求','直接报价','用 AARRR 经营'],
   answer:['B'], explain:'需求不明确先 SPIN 挖掘。'},

  /* ============ 第四阶 · 会选 ============ */
  {id:'c31',chapter:'会选',section:'单选',type:'single',dimension:'方法判断',difficulty:1,
   q:'"目标客户筛选"阶段应优先采用？',
   options:['STP、SWOT','SPIN','FABE','AARRR'],
   answer:['A'], explain:'筛选阶段用 STP、SWOT 判断值不值得。'},
  {id:'c32',chapter:'会选',section:'单选',type:'single',dimension:'方法判断',difficulty:1,
   q:'面对时间有限的高层决策者，最不合适的是？',
   options:['挑战式销售','3W 黄金圈','SCQA 结论先行','逐条功能讲解'],
   answer:['D'], explain:'高层时间有限，不宜逐条功能讲解。'},
  {id:'c33',chapter:'会选',section:'单选',type:'single',dimension:'方法判断',difficulty:1,
   q:'"签约后经营"阶段应采用？',
   options:['AARRR','SPIN','MEDDIC','SWOT'],
   answer:['A'], explain:'签约后用 AARRR 做留存扩展。'},
  {id:'c34',chapter:'会选',section:'单选',type:'single',dimension:'方法判断',difficulty:1,
   q:'面对采购与合规部门，最合适的是？',
   options:['NFABE + 安全机制说明','NFABI 现场演示','挑战式销售','游戏化运营'],
   answer:['A'], explain:'采购合规部门需结构化材料与可核查依据。'},
  {id:'c35',chapter:'会选',section:'判断',type:'judge',dimension:'方法判断',difficulty:1,
   q:'同一客户决策链上的不同角色，可以用同一套材料对接。',
   options:['对','错'], answer:['错'],
   explain:'不同角色关注点不同，须拆版本。'},
  {id:'c36',chapter:'会选',section:'判断',type:'judge',dimension:'方法判断',difficulty:1,
   q:'"只讲功能不讲利益"是常见误用之一。',
   options:['对','错'], answer:['对'],
   explain:'只讲功能不讲利益是常见误用。'},
  {id:'c37',chapter:'会选',section:'情景',type:'single',dimension:'方法判断',difficulty:2,
   q:'面对最关心"值不值、回报多少"的经济决策人（CIO），应？',
   options:['挑战式销售 + 投产比测算','NFABI 现场演示','SPIN 提问','AARRR 增长'],
   answer:['A'], explain:'经济决策人关心回报，用挑战式 + 投产比。'},
  {id:'c38',chapter:'会选',section:'情景',type:'single',dimension:'方法判断',difficulty:2,
   q:'发现某商机"找不到经济决策人、也没有内线支持者"，正确做法是？',
   options:['继续加大投入推进','用 MEDDIC 判定商机不成熟、暂缓','直接报价','换一个产品'],
   answer:['B'], explain:'缺经济决策人与内线，商机不成熟，应暂缓。'},

  /* ============ 综合考试 ============ */
  {id:'ce1',chapter:'综合考试',section:'客观题',type:'single',dimension:'产品知识',difficulty:1,score:3,
   q:'CosmoFreq 的定位是？',
   options:['医疗 AI 诊断','机构级科技创新与科技转化全生命周期智能平台','办公协同','专利数据库'],
   answer:['B'], explain:'机构级科技创新与科技转化全生命周期智能平台。'},
  {id:'ce2',chapter:'综合考试',section:'客观题',type:'fill',dimension:'产品知识',difficulty:1,score:3,
   q:'九大业务域中，"科创备案"之外还有哪几个？（举出三个即可）',
   answer:'招投标、项目管理、上架管控、知识产权、资质资格、课题研究、职称评审、荣誉赛事',
   keywords:['招投标','项目管理','上架管控','知识产权','资质资格','课题研究','职称评审','荣誉赛事'],
   explain:'九大业务域含科创备案、招投标、项目管理、上架管控、知识产权、资质资格、课题研究、职称评审、荣誉赛事。'},
  {id:'ce3',chapter:'综合考试',section:'客观题',type:'fill',dimension:'产品知识',difficulty:1,score:3,
   q:'七层架构中，夹在接入层与业务服务层之间的是哪一层？',
   answer:'合规门禁层', keywords:['合规门禁'], explain:'接入层与业务服务层之间是合规门禁层。'},
  {id:'ce4',chapter:'综合考试',section:'客观题',type:'single',dimension:'产品知识',difficulty:1,score:3,
   q:'三级授权中，"标书段落、交底书草稿"属哪个级别？',
   options:['低风险（自动放行）','中风险（人工审核）','高风险（多级签批）','无需授权'],
   answer:['B'], explain:'标书段落、交底书草稿属中风险，人工审核。'},
  {id:'ce5',chapter:'综合考试',section:'客观题',type:'fill',dimension:'产品知识',difficulty:1,score:3,
   q:'竞品对标里，定位为"知产 SaaS"的是？',
   answer:'智慧芽', keywords:['智慧芽'], explain:'定位"知产 SaaS"的竞品是智慧芽。'},
  {id:'ce6',chapter:'综合考试',section:'客观题',type:'fill',dimension:'产品知识',difficulty:1,score:3,
   q:'审计链五层防篡改中，防止"事后倒填时间"的是？',
   answer:'可信时间戳', keywords:['时间戳'], explain:'可信时间戳防止事后倒填时间。'},
  {id:'ce7',chapter:'综合考试',section:'客观题',type:'fill',dimension:'产品知识',difficulty:1,score:3,
   q:'多租户隔离中，最高敏感数据（PHI）采用？',
   answer:'加密隔离（Crypto-Sharding）', keywords:['加密隔离','crypto'], explain:'最高敏感数据 PHI 采用加密隔离 Crypto-Sharding。'},
  {id:'ce8',chapter:'综合考试',section:'客观题',type:'fill',dimension:'分析能力',difficulty:1,score:3,
   q:'STP 三步的先后顺序是？',
   answer:'细分 → 目标市场 → 定位', keywords:['细分','目标','定位'], explain:'STP：细分→目标市场→定位。'},
  {id:'ce9',chapter:'综合考试',section:'客观题',type:'fill',dimension:'分析能力',difficulty:1,score:3,
   q:'金字塔原理中，"以上统下"的含义是？',
   answer:'上层概括下层，下层支撑上层', keywords:['上层','下层','概括','支撑'], explain:'以上统下：上层概括下层，下层支撑上层。'},
  {id:'ce10',chapter:'综合考试',section:'客观题',type:'fill',dimension:'分析能力',difficulty:1,score:3,
   q:'黄金圈法则中，人们买的是"为什么"而非"做什么"，提出者是谁？',
   answer:'西蒙·斯涅克', keywords:['西蒙','斯涅克'], explain:'黄金圈法则提出者是西蒙·斯涅克。'},
  {id:'ce11',chapter:'综合考试',section:'客观题',type:'fill',dimension:'分析能力',difficulty:1,score:3,
   q:'卡诺模型五类需求分别是什么？',
   answer:'基本型、期望型、兴奋型、无差异型、反向型', keywords:['基本','期望','兴奋','无差异','反向'], explain:'五类：基本型/期望型/兴奋型/无差异型/反向型。'},
  {id:'ce12',chapter:'综合考试',section:'客观题',type:'fill',dimension:'销售技能',difficulty:1,score:3,
   q:'FABE 四个字母分别代表什么？',
   answer:'特征、优点、利益、证据', keywords:['特征','优点','利益','证据'], explain:'FABE = 特征/优点/利益/证据。'},
  {id:'ce13',chapter:'综合考试',section:'客观题',type:'fill',dimension:'销售技能',difficulty:1,score:3,
   q:'SCQA 四个字母分别代表什么？',
   answer:'情境、冲突、问题、答案', keywords:['情境','冲突','问题','答案'], explain:'SCQA = 情境/冲突/问题/答案。'},
  {id:'ce14',chapter:'综合考试',section:'客观题',type:'fill',dimension:'销售技能',difficulty:1,score:3,
   q:'AIDA 四阶段的顺序是？',
   answer:'注意→兴趣→欲望→行动', keywords:['注意','兴趣','欲望','行动'], explain:'AIDA：注意→兴趣→欲望→行动。'},
  {id:'ce15',chapter:'综合考试',section:'客观题',type:'fill',dimension:'销售技能',difficulty:1,score:3,
   q:'RAIN 中，N 代表什么？',
   answer:'新现实（New Reality）', keywords:['新现实','new reality'], explain:'RAIN 中 N = New Reality 新现实。'},
  {id:'ce16',chapter:'综合考试',section:'客观题',type:'fill',dimension:'销售技能',difficulty:1,score:3,
   q:'顾问式销售的核心起点是？',
   answer:'诊断客户问题', keywords:['诊断','问题'], explain:'顾问式销售核心起点是诊断客户问题。'},
  {id:'ce17',chapter:'综合考试',section:'客观题',type:'fill',dimension:'销售技能',difficulty:1,score:3,
   q:'SPIN 四类问题分别是什么？',
   answer:'情景、问题、暗示、需求-回报', keywords:['情景','问题','暗示','回报'], explain:'SPIN：情景/问题/暗示/需求-回报。'},
  {id:'ce18',chapter:'综合考试',section:'客观题',type:'fill',dimension:'销售技能',difficulty:1,score:3,
   q:'MEDDIC 六要素分别是什么？',
   answer:'量化指标、经济决策人、决策标准、决策流程、痛点识别、内线支持者', keywords:['量化指标','经济决策人','决策标准','决策流程','痛点','内线'], explain:'MEDDIC 六要素：量化指标/经济决策人/决策标准/决策流程/痛点识别/内线支持者。'},
  {id:'ce19',chapter:'综合考试',section:'客观题',type:'fill',dimension:'销售技能',difficulty:1,score:3,
   q:'AARRR 五级漏斗分别是什么？',
   answer:'获客、激活、留存、收入、推荐', keywords:['获客','激活','留存','收入','推荐'], explain:'AARRR：获客/激活/留存/收入/推荐。'},
  {id:'ce20',chapter:'综合考试',section:'客观题',type:'fill',dimension:'方法判断',difficulty:1,score:3,
   q:'"见客户就上 FABE 讲卖点"的常见误用应如何纠正？',
   answer:'先用 SPIN 摸底，再讲价值', keywords:['spin','摸底','价值'], explain:'纠正：先用 SPIN 摸底需求，再讲价值。'},
  {id:'ce21',chapter:'综合考试',section:'情景应用',type:'subjective',dimension:'方法判断',difficulty:3,score:5,
   q:'情景：药企客户自认需求明确（要科研管理平台），但市面方案同质化严重。你该用什么方法切入？为什么？',
   rubric:'用挑战式销售：客户自认需求明确但方案同质化，应 Teach（给新认知）、Tailor（定制）、Take Control（掌控节奏）。'},
  {id:'ce22',chapter:'综合考试',section:'情景应用',type:'subjective',dimension:'销售技能',difficulty:3,score:5,
   q:'情景：客户在演示现场明确表示"要看到才相信"。你该用什么方法推进？',
   rubric:'用 NFABI（冲击收尾）：现场演示让客户"看到"交底书 ≤5 分钟生成，用体验建立信任。'},
  {id:'ce23',chapter:'综合考试',section:'情景应用',type:'subjective',dimension:'方法判断',difficulty:3,score:5,
   q:'情景：你拿到一个商机，需要判断值不值得投入。你该用什么工具、看哪几个关键要素？',
   rubric:'用 MEDDIC：重点看 Metrics（量化价值）、Economic Buyer（经济决策人）、Champion（内线）三格是否填得出。'},
  {id:'ce24',chapter:'综合考试',section:'情景应用',type:'subjective',dimension:'分析能力',difficulty:3,score:5,
   q:'情景：你要向 CIO 做 10 分钟方案汇报，该用什么结构组织内容？',
   rubric:'用金字塔原理或 SCQA：结论先行，再展开提效/合规/转化三个支撑。'},
  {id:'ce25',chapter:'综合考试',section:'案例分析',type:'subjective',dimension:'方法判断',difficulty:3,score:10,
   q:'案例：某三甲医院成果转化率长期 5% 左右，信息科主任认可、愿做内线，最终拍板的是分管副院长。请设计推进策略（决策链角色、各用什么方法、如何帮内线内部说服）。',
   rubric:'决策链：使用者（信息科/科研处）、内线支持者（信息科主任）、经济决策人（分管副院长）。对内线用金字塔原理给"可转述的结构化材料"，对副院长用挑战式销售+SCQA结论先行+投产比测算，对使用科室用NFABI演示。整体用MEDDIC管理商机，确认Champion与Economic Buyer已锁定。'},
  {id:'ce26',chapter:'综合考试',section:'案例分析',type:'subjective',dimension:'销售技能',difficulty:3,score:10,
   q:'案例：某医疗 AI 企业，合规压力大（器械注册、等保），技术负责人主导、极度看重数据安全。请设计价值陈述方案（用什么框架、如何回应安全合规、哪些可承诺、哪些口径要谨慎）。',
   rubric:'技术型客户重数据，用 NFABE（数据证据收尾）。安全合规应答：明确"等保三级/密评已通过、国密SM2/SM3/SM4、数据分级L1-L5、审计链防篡改"为可承诺；但"数据绝对不出域"等须按部署形态（私有化vs SaaS）核对后再定口径，不得口头承诺具体数字。'}
  ]
});
