/* ============================================================
 * 天人道藏 · 题库数据
 * 来源：《天人道藏·营销培训评测考试体系（讲师版）》v1.0 2026-09-21
 * 五维能力：产品知识PK/分析能力AN/方法运用MA/场景判断SJ/结构化表达SE
 * ============================================================ */
window.SYSTEM_DEFS = window.SYSTEM_DEFS || [];
window.SYSTEM_DEFS.push({
  key:'trdz', name:'天人道藏', short:'天人道藏', icon:'📜', color:'#0ea5e9',
  sub:'基于 Web3.0 的全世界自然疗愈与生命科学古籍与数据共享共创平台',
  chapters:['懂产品','会分析','会卖','会选'],
  dimensions:['产品知识','分析能力','方法运用','场景判断','结构化表达'],
  exam:{ total:100, duration:120*60, pass:80, title:'综合考试（闭卷 · 100 分 · 120 分钟）' },
  bank:[
  /* ============ 模块一 · 懂产品 ============ */
  {id:'t1',chapter:'懂产品',section:'L1 记忆',type:'single',dimension:'产品知识',difficulty:1,
   q:'天人道藏的定位是？',
   options:['传统医学电商平台','基于 Web3.0 的全世界传统医学和医药共享共创平台','古籍扫描外包服务','互联网诊疗服务平台'],
   answer:['B'], explain:'定位是基于 Web3.0 的全世界传统医学和医药共享共创平台。'},
  {id:'t2',chapter:'懂产品',section:'L1 记忆',type:'single',dimension:'产品知识',difficulty:1,
   q:'天人道藏的业务闭环是？',
   options:['生产—销售—售后','古籍数字化 → 众包校对 → 数据集共享交易 → 贡献确权激励','广告—流量—变现','融资—研发—上市'],
   answer:['B'], explain:'闭环：古籍数字化→众包校对→数据集共享交易→贡献确权激励。'},
  {id:'t3',chapter:'懂产品',section:'L1 记忆',type:'single',dimension:'产品知识',difficulty:1,
   q:'下列不属于五大内容体系的是？',
   options:['全球传统医学','儒家经典','西方现代医学','道家经典'],
   answer:['C'], explain:'西方现代医学不属于五大内容体系（全球传统医学/儒家经典/道家经典等）。'},
  {id:'t4',chapter:'懂产品',section:'L1 记忆',type:'single',dimension:'产品知识',difficulty:1,
   q:'首页三个核心入口是？',
   options:['开始阅读 / 医典校对 / 我要共享','购物车 / 支付 / 客服','上传 / 下载 / 搜索','注册 / 登录 / 退出'],
   answer:['A'], explain:'首页三入口：开始阅读 / 医典校对 / 我要共享。'},
  {id:'t5',chapter:'懂产品',section:'L1 记忆',type:'single',dimension:'产品知识',difficulty:1,
   q:'关于平台积分，正确的说法是？',
   options:['可提现为现金','是可交易的数字资产','不能提现、非数字资产，是贡献计量记录','可兑换诊疗服务'],
   answer:['C'], explain:'积分不能提现、非数字资产，是贡献计量记录。'},
  {id:'t6',chapter:'懂产品',section:'L1 记忆',type:'judge',dimension:'产品知识',difficulty:1,
   q:'天人道藏平台向用户提供疾病诊断与治疗建议。',
   options:['对','错'], answer:['错'],
   explain:'平台不提供疾病诊断与治疗建议，内容仅供研究参考（医疗免责合规口径）。'},
  {id:'t7',chapter:'懂产品',section:'L1 记忆',type:'judge',dimension:'产品知识',difficulty:1,
   q:'用户上传内容后即可在前台看到。',
   options:['对','错'], answer:['错'],
   explain:'内容上架需满足三个条件：审核通过、质量核验完成、状态上架。'},
  {id:'t8',chapter:'懂产品',section:'L1 记忆',type:'judge',dimension:'产品知识',difficulty:1,
   q:'平台会员到期后自动续费。',
   options:['对','错'], answer:['错'],
   explain:'会员到期不自动续费。'},
  {id:'t9',chapter:'懂产品',section:'L1 记忆',type:'judge',dimension:'产品知识',difficulty:1,
   q:'阅读进度保存在账号云端，换设备自动同步。',
   options:['对','错'], answer:['错'],
   explain:'阅读进度并非保存云端自动同步（按资料口径）。'},
  {id:'t10',chapter:'懂产品',section:'L2 应用',type:'fill',dimension:'产品知识',difficulty:2,
   q:'机构入驻需填写机构名称、________ 并上传证明材料。',
   answer:'统一社会信用代码', keywords:['信用代码','社会信用','统一社会'], explain:'机构入驻需填写机构名称、统一社会信用代码并上传证明材料。'},
  {id:'t11',chapter:'懂产品',section:'L2 应用',type:'fill',dimension:'产品知识',difficulty:2,
   q:'内容上架需同时满足的三个条件：________、质量核验完成、________。',
   answer:'审核通过；状态上架', keywords:['审核通过','状态上架','审核','上架'], explain:'三条件：审核通过、质量核验完成、状态上架。'},
  {id:'t12',chapter:'懂产品',section:'L2 应用',type:'fill',dimension:'产品知识',difficulty:2,
   q:'校对分级标注共 L1–L4，其中 L1（基础层）对应的是________（举一类即可）。',
   answer:'标点 / 分段 / 明显错字（任一）', keywords:['标点','分段','错字'], explain:'L1 基础层对应标点、分段、明显错字等基础校对。'},
  {id:'t13',chapter:'懂产品',section:'L3 场景',type:'subjective',dimension:'产品知识',difficulty:3, score:5,
   q:'客户问"我的数据存放在哪里、谁能看到"，你应引用哪部分资料、给出什么方向的回答？',
   rubric:'引用《业务资料》信息安全与隐私机制部分；答出"加密 / 权限分级 / 仅本人与管理员可见"等要点。'},
  {id:'t14',chapter:'懂产品',section:'L3 场景',type:'subjective',dimension:'产品知识',difficulty:3, score:5,
   q:'客户问"你们平台能治我的病吗"，正确且合规的回答是什么？',
   rubric:'不提供诊疗建议，内容仅供研究参考（合规口径）。'},

  /* ============ 模块二 · 会分析 ============ */
  {id:'t15',chapter:'会分析',section:'L1 记忆',type:'single',dimension:'分析能力',difficulty:1,
   q:'STP 中的 P 指？',
   options:['价格 Price','定位 Positioning','推广 Promotion','产品 Product'],
   answer:['B'], explain:'P = Positioning 定位。'},
  {id:'t16',chapter:'会分析',section:'L1 记忆',type:'single',dimension:'分析能力',difficulty:1,
   q:'下列不属于经典 4P 的是？',
   options:['产品','价格','人员 People','渠道'],
   answer:['C'], explain:'经典 4P = 产品/价格/渠道/推广；人员 People 属 7P。'},
  {id:'t17',chapter:'会分析',section:'L1 记忆',type:'single',dimension:'结构化表达',difficulty:1,
   q:'金字塔原理最核心的一条是？',
   options:['结论先行','数据优先','故事优先','图表优先'],
   answer:['A'], explain:'金字塔原理最核心的是结论先行。'},
  {id:'t18',chapter:'会分析',section:'L1 记忆',type:'single',dimension:'分析能力',difficulty:1,
   q:'SWOT 中的 S 指？',
   options:['系统','优势 Strengths','策略','销售'],
   answer:['B'], explain:'S = Strengths 优势。'},
  {id:'t19',chapter:'会分析',section:'L2 应用',type:'subjective',dimension:'分析能力',difficulty:2,
   q:'用一句话写清天人道藏的定位陈述（STP 的 P）。',
   rubric:'含"全球传统医学 + 共创共享 + 科研基础设施 / 确权激励"等定位要素。'},
  {id:'t20',chapter:'会分析',section:'L2 应用',type:'subjective',dimension:'分析能力',difficulty:2,
   q:'列举天人道藏的"渠道（Place）"至少三项。',
   rubric:'Web 端 / H5 / API 开放平台 / 机构通道（答出 3 项即可）。'},
  {id:'t21',chapter:'会分析',section:'L2 应用',type:'subjective',dimension:'结构化表达',difficulty:2,
   q:'用金字塔原理，把"天人道藏有五大内容体系、全文检索、时空图谱"改写成"结论先行"的一句话。',
   rubric:'结论先行——先给价值结论，再列支撑。'},
  {id:'t22',chapter:'会分析',section:'L2 应用',type:'subjective',dimension:'分析能力',difficulty:2,
   q:'写出天人道藏的一个"威胁（Threat）"。',
   rubric:'WHO TMGL / 元堂 / 竞品卡位（任一）。'},
  {id:'t23',chapter:'会分析',section:'L2 应用',type:'subjective',dimension:'分析能力',difficulty:2,
   q:'用 3W 黄金圈，写出天人道藏的 Why（为什么做）。',
   rubric:'"让下一次青蒿素式发现从偶然变为必然"或"让传统医学智慧被看见、被验证、被激励"。'},
  {id:'t24',chapter:'会分析',section:'L2 应用',type:'subjective',dimension:'分析能力',difficulty:2,
   q:'用卡诺模型，把"免费在线阅读"归类到哪一型，并说明理由。',
   rubric:'基本型；理由"必须有，缺了流失，做好了不加分"。'},
  {id:'t25',chapter:'会分析',section:'L3 场景',type:'single',dimension:'分析能力',difficulty:3, score:5,
   q:'客户说"你们的方案和市面上同类平台差不多"，你该用哪个（些）模型先做形势研判？',
   options:['AIDA','SWOT（形势研判）+ 挑战式销售（给新认知）','AARRR','只讲情怀'],
   answer:['B'], explain:'形势研判用 SWOT，再配挑战式销售给新认知。'},
  {id:'t26',chapter:'会分析',section:'L3 场景',type:'single',dimension:'结构化表达',difficulty:3, score:5,
   q:'向客户高层做一次 15 分钟的方案汇报，你会优先用哪个理论组织表达？为什么？',
   options:['时间顺序罗列','金字塔原理 / SCQA（高层时间有限、需结论先行）','随机发挥','从细节讲起'],
   answer:['B'], explain:'高层时间有限，用金字塔原理/SCQA 结论先行。'},

  /* ============ 模块三 · 会卖 ============ */
  {id:'t27',chapter:'会卖',section:'L1 字母',type:'single',dimension:'方法运用',difficulty:1,
   q:'FABE 中的 E 指？',
   options:['需求','证据 Evidence','体验','期望'],
   answer:['B'], explain:'E = Evidence 证据。'},
  {id:'t28',chapter:'会卖',section:'L1 字母',type:'single',dimension:'方法运用',difficulty:1,
   q:'SPIN 中的 I 指？',
   options:['情景问题','问题问题','暗示问题 Implication','需求-回报问题'],
   answer:['C'], explain:'I = Implication 暗示问题。'},
  {id:'t29',chapter:'会卖',section:'L1 字母',type:'single',dimension:'方法运用',difficulty:1,
   q:'MEDDIC 中的 E 指？',
   options:['痛点','经济决策人 Economic buyer','内线','指标'],
   answer:['B'], explain:'E = Economic buyer 经济决策人。'},
  {id:'t30',chapter:'会卖',section:'L1 字母',type:'single',dimension:'方法运用',difficulty:1,
   q:'AARRR 最后一个 R 指？',
   options:['收入','留存','推荐 Referral','获客'],
   answer:['C'], explain:'AARRR 最后一个 R = Referral 推荐。'},
  {id:'t31',chapter:'会卖',section:'L2 应用',type:'subjective',dimension:'方法运用',difficulty:2,
   q:'面对"重证据、重逻辑"的技术型客户，优先用哪个（些）方法？',
   rubric:'NFABE / SPIN / FABE（重证据）。'},
  {id:'t32',chapter:'会卖',section:'L2 应用',type:'subjective',dimension:'方法运用',difficulty:2,
   q:'客户有明显痛点但购买意愿尚未明确，优先用哪个方法唤醒需求？',
   rubric:'PFABNE（痛点开场唤醒需求）。'},
  {id:'t33',chapter:'会卖',section:'L2 应用',type:'subjective',dimension:'方法运用',difficulty:2,
   q:'客户自认需求明确、但方案同质化严重，优先用哪个方法？',
   rubric:'挑战式销售（先给新认知）。'},
  {id:'t34',chapter:'会卖',section:'L2 应用',type:'subjective',dimension:'方法运用',difficulty:2,
   q:'把"平台有全文检索功能"改写成一句以客户利益收尾的 FABE 表达。',
   rubric:'落到客户利益收尾（如"几分钟找到跨越千年的知识连接"）。'},
  {id:'t35',chapter:'会卖',section:'L3 场景',type:'single',dimension:'方法运用',difficulty:3, score:5,
   q:'面对时间紧、需数据支撑的科研机构决策者，你会优先？',
   options:['直接讲产品功能','先确认需求，再讲特征利益、以证据收尾','先讲品牌愿景','直接报价格'],
   answer:['B'], explain:'理性型决策者：先确认需求，再讲特征利益、以证据收尾。'},
  {id:'t36',chapter:'会卖',section:'L3 场景',type:'single',dimension:'方法运用',difficulty:3, score:5,
   q:'面对"先看到再相信"的体验型客户，你倾向用什么收尾？',
   options:['数据证据','现场演示与冲击（时空图谱/青蒿素指数）','合同条款','报价单'],
   answer:['B'], explain:'体验型客户用 NFABI 现场演示冲击收尾。'},
  {id:'t37',chapter:'会卖',section:'L3 场景',type:'single',dimension:'方法运用',difficulty:3, score:5,
   q:'客户反复比价压价、推进节奏失控，你的第一反应是？',
   options:['再降一次价','相互设限、主动设定资格条件','放弃这个客户','让步换订单'],
   answer:['B'], explain:'用桑德勒相互设限、主动设定资格条件。'},
  {id:'t38',chapter:'会卖',section:'L3 场景',type:'single',dimension:'方法运用',difficulty:3, score:5,
   q:'客户需求模糊、需要专业引导，你倾向？',
   options:['结构化提问诊断，共同形成方案','直接给一套标准方案','反复强调产品优势','等客户想清楚再来'],
   answer:['A'], explain:'顾问式：结构化提问诊断，共同形成方案。'},

  /* ============ 模块四 · 会选 ============ */
  {id:'t39',chapter:'会选',section:'L3 场景',type:'single',dimension:'场景判断',difficulty:2, score:5,
   q:'初次接触与需求摸底阶段，优先用？',
   options:['MEDDIC','SPIN + 3W 黄金圈','AARRR','只讲价格'],
   answer:['B'], explain:'初次接触摸底用 SPIN + 3W 黄金圈。'},
  {id:'t40',chapter:'会选',section:'L3 场景',type:'single',dimension:'场景判断',difficulty:2, score:5,
   q:'方案陈述阶段，优先用？',
   options:['SPIN','NFABE / FABE / SCQA / 金字塔原理','桑德勒','AIDA'],
   answer:['B'], explain:'方案陈述用 NFABE/FABE/SCQA/金字塔原理。'},
  {id:'t41',chapter:'会选',section:'L3 场景',type:'single',dimension:'场景判断',difficulty:2, score:5,
   q:'签约后的客户持续经营，优先用？',
   options:['AARRR','MEDDIC','SPIN','SWOT'],
   answer:['A'], explain:'签约后经营用 AARRR。'},
  {id:'t42',chapter:'会选',section:'L3 场景',type:'single',dimension:'场景判断',difficulty:2, score:5,
   q:'对手在商机评估与资源分配阶段，优先用？',
   options:['MEDDIC + 卡诺模型','FABE','AIDA','黄金圈'],
   answer:['A'], explain:'商机评估与资源分配用 MEDDIC + 卡诺模型。'},
  {id:'t43',chapter:'会选',section:'L3 场景',type:'single',dimension:'场景判断',difficulty:2, score:5,
   q:'演示与体验环节，优先用？',
   options:['NFABI + FABE','MEDDIC','挑战式','SWOT'],
   answer:['A'], explain:'演示体验用 NFABI + FABE。'},
  {id:'t44',chapter:'会选',section:'L3 场景',type:'single',dimension:'场景判断',difficulty:2, score:5,
   q:'"见客户就上 FABE 讲卖点"属于常见误用，正确做法是？',
   options:['先 SPIN 摸底再讲价值','继续加码','换客户','只发资料'],
   answer:['A'], explain:'先 SPIN 摸底需求再讲价值。'},
  {id:'t45',chapter:'会选',section:'L4 综合案例',type:'subjective',dimension:'场景判断',difficulty:3, score:10,
   q:'案例：某省级中医药研究院，馆藏大量散落古籍与方剂数据，希望在政策窗口期完成数字化与数据确权。用 SPIN 为本次拜访设计开场提问（至少 4 个问题，按 S→P→I→N 顺序）。',
   rubric:'S 情境（了解现状）、P 问题（发现困难）、I 暗示（让客户意识到代价）、N 需求-回报（描绘价值）四类各一问，顺序正确。'},
  {id:'t46',chapter:'会选',section:'L4 综合案例',type:'subjective',dimension:'结构化表达',difficulty:3, score:10,
   q:'案例：同上。分别对院长（关心"值不值"）、信息中心主任（关心"稳不稳"）、一线研究员（关心"好不好用"）各设计一段话术，说明用了什么方法、为什么。',
   rubric:'院长=经济决策人→讲价值/ROI；信息中心主任=技术评估者→讲安全稳定/数据确权；研究员=使用者→讲好用/效率。三角色话术按关注点区分，方法选用正确。'},
  {id:'t47',chapter:'会选',section:'L4 综合案例',type:'subjective',dimension:'场景判断',difficulty:3, score:10,
   q:'案例：同上。用 MEDDIC 对这个商机做一次资格评估，写出六个维度的判断。',
   rubric:'MEDDIC 六维：Metrics 量化指标、Economic buyer 经济决策人、Decision criteria 决策标准、Decision process 决策流程、Identify pain 痛点识别、Champion 内线支持者，各给出判断。'}
  ]
});
