/* ============================================================
 * 超级大脑营销培训 · 练习评测题库数据
 * 来源：《超级大脑营销培训·练习评测与考试手册》V1.0
 * 共 99 题：86 客观题 + 13 主观题
 * 题型：single(单选) multi(多选) judge(判断) fill(填空) subjective(主观)
 * 维度：知识/分析/表达/流程/选择/合规
 * ============================================================ */

window.SYSTEM_DEFS = window.SYSTEM_DEFS || [];
window.SYSTEM_DEFS.push({
  key:'sb', name:'超级大脑', short:'超级大脑', icon:'🧠', color:'#2563eb',
  sub:'企业级 AI 原生知识引擎',
  chapters:["阶段一 · 懂产品","阶段二 · 会分析","阶段三 · 会卖","阶段四 · 会选","综合考试"],
  dimensions:["知识","分析","表达","流程","选择","合规"],
  exam:{ total:100, duration:90*60, pass:80, title:'综合考试（闭卷 · 100 分 · 90 分钟 · 80 分通过）' },
  bank:[
  /* ================= 阶段一 · 懂产品 · 随堂练习 ================= */
  { id:"s1a1", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"single", dimension:"知识", difficulty:1,
    q:"超级大脑的产品定位是？",
    options:["企业网盘","在线协作文档","企业级 AI 原生知识引擎","通用大模型助手"],
    answer:["C"],
    explain:"超级大脑定位为企业级 AI 原生知识引擎，不是网盘、协作文档或通用大模型助手。" },
  { id:"s1a2", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"single", dimension:"知识", difficulty:1,
    q:"知识飞轮模型的四环顺序是？",
    options:["采集 → 应用 → 解析 → 图谱","采集 → 解析 → 图谱 → 应用","解析 → 采集 → 应用 → 图谱","图谱 → 采集 → 解析 → 应用"],
    answer:["B"],
    explain:"知识飞轮四环：采集 → 解析 → 图谱 → 应用，依次递进。" },
  { id:"s1a3", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"single", dimension:"知识", difficulty:1,
    q:"私有化部署的标准上线耗时口径是？",
    options:["3 天","8 小时","30 分钟","1 周"],
    answer:["C"],
    explain:"私有化部署标准上线耗时口径为 30 分钟，这是对外统一口径。" },
  { id:"s1a4", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"multi", dimension:"知识", difficulty:1,
    q:"下列属于八大能力域的是？（多选）",
    options:["RAG 智能问答","知识图谱","多源数据采集","版本管理与审核流","视频会议","即时通讯"],
    answer:["A","B","C","D"],
    explain:"八大能力域含 RAG 智能问答、知识图谱、多源数据采集、版本管理与审核流等；视频会议、即时通讯不属于。" },
  { id:"s1a5", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"single", dimension:"知识", difficulty:1,
    q:"企业空间文件入库的标准流转路径是？",
    options:["上传 → 生效","上传 → 解析 → 审核 → 入向量库","上传 → 审核 → 解析","解析 → 上传 → 入向量库"],
    answer:["B"],
    explain:"企业空间文件走：上传 → 解析 → 审核 → 入向量库。私人空间免审核。" },
  { id:"s1a6", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"single", dimension:"知识", difficulty:1,
    q:"单文件大小上限是？",
    options:["50MB","100MB","200MB","500MB"],
    answer:["B"],
    explain:"单文件大小上限为 100MB。" },
  { id:"s1a7", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"judge", dimension:"知识", difficulty:1,
    q:"私人空间上传的文件需要审核通过后才能被检索。",
    options:["对","错"],
    answer:["错"],
    explain:"私人空间免审核、上传后直接可用；只有企业空间才走「上传 → 解析 → 审核 → 入向量库」。" },
  { id:"s1a8", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"judge", dimension:"知识", difficulty:1,
    q:"开放平台数据面接口（检索与问答）已经对外提供，可以现场承诺给客户。",
    options:["对","错"],
    answer:["错"],
    explain:"开放平台数据面接口属「规划中」能力，不构成交付承诺，现场不得承诺。" },
  { id:"s1a9", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"single", dimension:"知识", difficulty:1,
    q:"下列哪一项不属于四类知识空间？",
    options:["私人空间","团队空间","共享空间","公共网盘"],
    answer:["D"],
    explain:"四类知识空间为私人、团队、共享、企业公共知识库；「公共网盘」不是。" },
  { id:"s1a10", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"single", dimension:"知识", difficulty:1,
    q:"企业公共知识库对普通成员的访问级别是？",
    options:["owner","manage","edit","use（只读）"],
    answer:["D"],
    explain:"普通成员对企业公共知识库为 use（只读）级别。" },
  { id:"s1a11", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"multi", dimension:"知识", difficulty:1,
    q:"三类优先目标客户画像是？（多选）",
    options:["合规敏感型金融机构","知识密集型制造企业","快速扩张型科技与 SaaS 企业","个体自由职业者"],
    answer:["A","B","C"],
    explain:"三类优先客户：合规敏感型金融机构、知识密集型制造企业、快速扩张型科技与 SaaS 企业。" },
  { id:"s1a12", chapter:"阶段一 · 懂产品", section:"随堂练习", type:"fill", dimension:"知识", difficulty:1,
    q:"超级大脑的一句话对外表述是：让企业的每一份知识，都成为______。",
    answer:"AI 的智慧",
    keywords:["智慧","ai","AI"],
    explain:"统一对外口号：让企业的每一份知识，都成为 AI 的智慧。" },

  /* ================= 阶段一 · 懂产品 · 阶段评测 ================= */
  { id:"s1b1", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"single", dimension:"合规", difficulty:2,
    q:"客户问「我们的文档会不会被拿去训练你们的大模型」，正确回答是？",
    options:["一般不会，特殊情况可能","不会，客户数据不用于训练或微调任何大模型","这个不重要","视合同而定，现场可以口头保证"],
    answer:["B"],
    explain:"口径：客户数据不用于训练或微调任何大模型，须坚定、明确，不给模糊空间。" },
  { id:"s1b2", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"single", dimension:"合规", difficulty:2,
    q:"客户要求现场给出「一年投产比是多少」，正确做法是？",
    options:["按最好的案例报一个数","用四维测算方法讲解，并说明具体数值须商务与财务确认口径，以「待确认」表述","现场估算一个保守数字并注明免责","拒绝回答"],
    answer:["B"],
    explain:"投产比只给四维测算方法，数值是「方法演示、非承诺」，口径待商务与财务确认。" },
  { id:"s1b3", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"single", dimension:"知识", difficulty:1,
    q:"「2–4 周交付、品牌 Logo 名称主题色替换」对应哪种交付模式？",
    options:["SaaS 订阅","私有化部署","OEM 贴牌","ODM 定制"],
    answer:["C"],
    explain:"2–4 周交付 + 品牌 Logo/名称/主题色替换，是 OEM 贴牌模式的特征。" },
  { id:"s1b4", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"multi", dimension:"合规", difficulty:2,
    q:"下列属于「规划中」能力、对外不得承诺的是？（多选）",
    options:["短信网关接入（内测期用固定验证码）","第三方账号登录（企微/钉钉/飞书/微信）","开放平台数据面接口","MCP 协议接入","私有化部署","知识图谱"],
    answer:["A","B","C","D"],
    explain:"短信网关、第三方登录、开放平台数据面、MCP 均为「规划中」，不承诺交付；私有化部署、知识图谱是已具备能力。" },
  { id:"s1b5", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"subjective", dimension:"表达", difficulty:2,
    q:"用三段话向客户讲清「我们是什么、对你有什么好处、你要付出什么」。",
    rubric:"① 是什么：企业级 AI 原生知识引擎 + 知识飞轮四环（1 分）；② 好处：至少 1 个直接价值（检索效率 10 倍 / 上手周期缩短 50% / 引用溯源）+ 1 个间接或战略价值（1 分）；③ 付出：金钱 + 配合事项（知识管理员 / 首批文档）各点到（1 分）。出现具体价格数字且未标「待确认」→ 本题直接 0 分（合规一票否决）。" },
  { id:"s1b6", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"judge", dimension:"知识", difficulty:1,
    q:"私有化部署下数据不出客户内网，且支持气隙（完全离线）部署。",
    options:["对","错"],
    answer:["对"],
    explain:"私有化部署数据不出内网，并支持气隙（完全离线）环境。" },
  { id:"s1b7", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"single", dimension:"知识", difficulty:2,
    q:"知识引擎回答的相关度为 82% 时，正确的处理建议是？",
    options:["直接对外引用，无需核对","可直接采信，必要时点「查看原文」核对细节","说明知识库覆盖不足","当作无匹配处理"],
    answer:["B"],
    explain:"82% 属高相关度，可直接采信，但必要时应「查看原文」核对细节。" },
  { id:"s1b8", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"single", dimension:"知识", difficulty:1,
    q:"企业端接口返回 403 的含义是？",
    options:["账号密码错误","令牌过期","无对应权限键，接口拦截","网络故障"],
    answer:["C"],
    explain:"403 = 无对应权限键、接口拦截；账号错误/令牌过期/网络故障分别对应其他状态码。" },
  { id:"s1b9", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"multi", dimension:"知识", difficulty:2,
    q:"「三层权限防线」指的是哪三层？（多选）",
    options:["接口级（权限键校验）","知识库级（五档访问级别）","文件级（归属校验）","网络级（防火墙）"],
    answer:["A","B","C"],
    explain:"三层权限防线 = 接口级（权限键）+ 知识库级（五档访问级别）+ 文件级（归属校验）；网络级防火墙不属于。" },
  { id:"s1b10", chapter:"阶段一 · 懂产品", section:"阶段评测", type:"subjective", dimension:"合规", difficulty:3,
    q:"客户安全部门问：「你们有没有通过等级保护测评、拿到等保证书？」请写出正确回答口径。",
    rubric:"① 答出「系统按等保标准技术要求设计并落地，配合客户定级、备案与测评」（2 分）；② 答出「不宣称已取得特定等级保护证书」（2 分）；③ 承诺了证书或测评结果 → 0 分（合规一票否决）。" },

  /* ================= 阶段二 · 会分析 · 随堂练习 ================= */
  { id:"s2a1", chapter:"阶段二 · 会分析", section:"随堂练习", type:"single", dimension:"分析", difficulty:1,
    q:"STP 理论的正确顺序是？",
    options:["定位 → 细分 → 目标","细分 → 目标 → 定位","目标 → 定位 → 细分","细分 → 定位 → 目标"],
    answer:["B"],
    explain:"STP = Segmentation 细分 → Targeting 目标 → Positioning 定位。" },
  { id:"s2a2", chapter:"阶段二 · 会分析", section:"随堂练习", type:"single", dimension:"分析", difficulty:1,
    q:"3W 黄金圈法则的表达顺序是？",
    options:["What → How → Why","Why → How → What","How → Why → What","Why → What → How"],
    answer:["B"],
    explain:"3W 黄金圈由内向外：Why → How → What，先讲为什么再讲怎么做和是什么。" },
  { id:"s2a3", chapter:"阶段二 · 会分析", section:"随堂练习", type:"single", dimension:"分析", difficulty:1,
    q:"SWOT 中「机会（O）」考察的是？",
    options:["我们内部已有的能力","对未来而言的外部变化","与竞对对比的现在","客户对我们的评价"],
    answer:["B"],
    explain:"机会 O 与威胁 T 是「对未来而言的外部变化」；优势 S 劣势 W 是与竞对对比的「现在」。" },
  { id:"s2a4", chapter:"阶段二 · 会分析", section:"随堂练习", type:"judge", dimension:"分析", difficulty:1,
    q:"金字塔原理要求结论先行、以上统下。",
    options:["对","错"],
    answer:["对"],
    explain:"金字塔原理核心：结论先行、以上统下、归类分组、逻辑递进。" },
  { id:"s2a5", chapter:"阶段二 · 会分析", section:"随堂练习", type:"single", dimension:"分析", difficulty:1,
    q:"卡诺模型中「做不好会被淘汰、做好了也不会加分」的是哪类需求？",
    options:["兴奋型","期望型","基本型","无差异型"],
    answer:["C"],
    explain:"基本型需求：不做会被淘汰、做好也不加分，是底线要求。" },
  { id:"s2a6", chapter:"阶段二 · 会分析", section:"随堂练习", type:"single", dimension:"分析", difficulty:1,
    q:"4P 营销理论的四个 P 是？",
    options:["产品、价格、渠道、推广","产品、人员、流程、价格","定位、价格、渠道、促销","产品、利润、伙伴、流程"],
    answer:["A"],
    explain:"4P = Product 产品、Price 价格、Place 渠道、Promotion 推广。" },
  { id:"s2a7", chapter:"阶段二 · 会分析", section:"随堂练习", type:"fill", dimension:"分析", difficulty:2,
    q:"本产品 SWOT 的应对思路是：把「______」作为第一叙事，而非模型能力。",
    answer:"治理深度",
    keywords:["治理"],
    explain:"SWOT 应对思路把「治理深度」作为第一叙事，而非模型能力——模型是所有参与者的共同上游。" },
  { id:"s2a8", chapter:"阶段二 · 会分析", section:"随堂练习", type:"multi", dimension:"分析", difficulty:1,
    q:"关于 SWOT 的使用纪律，正确的有？（多选）",
    options:["必须落到行动结论，不能只填四格","优势劣势是与竞对对比而言的现在","机会威胁是对未来而言的外部变化","劣势应该重点讲给客户听，体现坦诚"],
    answer:["A","B","C"],
    explain:"SWOT 须落到行动结论；S/W 是现在、O/T 是未来；劣势对外用中性「相对短板」，不是重点讲给客户听。" },

  /* ================= 阶段二 · 会分析 · 阶段评测 ================= */
  { id:"s2b1", chapter:"阶段二 · 会分析", section:"阶段评测", type:"single", dimension:"分析", difficulty:2,
    q:"高层决策者只有 10 分钟，开场应该用什么结构？",
    options:["功能清单逐一介绍","3W 黄金圈：先讲 Why，再 How，最后 What","先问预算再讲产品","直接演示全部功能"],
    answer:["B"],
    explain:"高层时间有限，用 3W 黄金圈先讲 Why（痛点价值），再 How、What。" },
  { id:"s2b2", chapter:"阶段二 · 会分析", section:"阶段评测", type:"single", dimension:"分析", difficulty:2,
    q:"客户需求清单里有一条「数据不出内网」。按卡诺模型它属于？",
    options:["兴奋型","基本型","期望型","无差异型"],
    answer:["B"],
    explain:"数据不出内网是安全底线，属基本型需求（做不好会被淘汰）。" },
  { id:"s2b3", chapter:"阶段二 · 会分析", section:"阶段评测", type:"subjective", dimension:"表达", difficulty:3,
    q:"用 SCQA 框架为超级大脑写四句方案开篇（S 情境 / C 冲突 / Q 问题 / A 答案各一句）。",
    rubric:"① S 用共识开场（知识资产在增长之类）（1 分）；② C 打破共识（调得动的知识在变少 / 大模型答案不敢信）（1 分）；③ Q 把冲突转化为问题（1 分）；④ A 指向知识飞轮（1 分）；⑤ 四句连贯、有客户感（1 分）。" },
  { id:"s2b4", chapter:"阶段二 · 会分析", section:"阶段评测", type:"single", dimension:"分析", difficulty:2,
    q:"公司只发了推广内容、没有安排渠道承接，按 4P 检查缺的是哪个 P？",
    options:["Product","Price","Place","Promotion"],
    answer:["C"],
    explain:"发了推广（Promotion）但没有渠道承接，缺的是 Place（渠道）。" },
  { id:"s2b5", chapter:"阶段二 · 会分析", section:"阶段评测", type:"judge", dimension:"分析", difficulty:1,
    q:"SWOT 分析只要把四个格子填满就算完成。",
    options:["对","错"],
    answer:["错"],
    explain:"SWOT 必须落到行动结论，只填四格不算完成。" },
  { id:"s2b6", chapter:"阶段二 · 会分析", section:"阶段评测", type:"multi", dimension:"分析", difficulty:2,
    q:"本产品 STP 三维细分模型的三个维度是？（多选）",
    options:["行业","规模","场景","地域"],
    answer:["A","B","C"],
    explain:"STP 三维细分：行业 × 规模 × 场景。" },
  { id:"s2b7", chapter:"阶段二 · 会分析", section:"阶段评测", type:"single", dimension:"选择", difficulty:2,
    q:"竞标前需要研判竞争形势，优先用哪组方法？",
    options:["AIDA、4P","SWOT、挑战式销售","AARRR、卡诺","FABE、SPIN"],
    answer:["B"],
    explain:"竞争性对抗阶段优先用 SWOT、挑战式销售。" },
  { id:"s2b8", chapter:"阶段二 · 会分析", section:"阶段评测", type:"subjective", dimension:"分析", difficulty:2,
    q:"把「知识图谱可视化」按卡诺模型分类，并说明对应的投入策略。",
    rubric:"① 分类正确：知识图谱可视化 = 兴奋型（2 分）；② 理由：没有不扣分、有了是惊喜、超客户对「知识库」的预期（1 分）；③ 投入策略：重点安排演示环节，不做全员加班式投入（1 分）；④ 提到分类会随时间漂移（1 分）。" },

  /* ================= 阶段三 · 会卖 · 随堂练习 ================= */
  { id:"s3a1", chapter:"阶段三 · 会卖", section:"随堂练习", type:"single", dimension:"表达", difficulty:1,
    q:"FABE 法则中的 E 指？",
    options:["经验（Experience）","证据（Evidence）","情感（Emotion）","环境（Environment）"],
    answer:["B"],
    explain:"FABE = Feature 特征、Advantage 优点、Benefit 利益、Evidence 证据。" },
  { id:"s3a2", chapter:"阶段三 · 会卖", section:"随堂练习", type:"single", dimension:"表达", difficulty:1,
    q:"NFABI 与 NFABE 的最大差别是？",
    options:["开头不同","收尾不同：一个以证据收、一个以冲击体验收","完全没有差别","NFABI 少一个环节"],
    answer:["B"],
    explain:"NFABE 以证据（E）收尾，NFABI 以冲击体验（I=Impact）收尾。" },
  { id:"s3a3", chapter:"阶段三 · 会卖", section:"随堂练习", type:"single", dimension:"流程", difficulty:2,
    q:"SPIN 提问法中，被称为精华的第三类问题是？",
    options:["情景问题","难点问题","暗示问题——让客户自己意识到代价","需求-回报问题"],
    answer:["C"],
    explain:"SPIN 第三类暗示问题（Implication）让客户自己意识到代价，是精华。" },
  { id:"s3a4", chapter:"阶段三 · 会卖", section:"随堂练习", type:"single", dimension:"流程", difficulty:1,
    q:"MEDDIC 中的 E 指？",
    options:["证据（Evidence）","经济决策人（Economic buyer）","期望（Expectation）","效率（Efficiency）"],
    answer:["B"],
    explain:"MEDDIC = Metrics、Economic buyer、Decision criteria、Decision process、Identify pain、Champion；E 是经济决策人。" },
  { id:"s3a5", chapter:"阶段三 · 会卖", section:"随堂练习", type:"judge", dimension:"知识", difficulty:1,
    q:"AARRR 是销售话术模型，应该在见客户时使用。",
    options:["对","错"],
    answer:["错"],
    explain:"AARRR 是增长运营漏斗模型，已【归位】移出销售话术，用于签约后经营。" },
  { id:"s3a6", chapter:"阶段三 · 会卖", section:"随堂练习", type:"single", dimension:"流程", difficulty:1,
    q:"挑战式销售的三要素是？",
    options:["提问、倾听、总结","教导、定制、掌控","关系、痛点、方案","注意、兴趣、行动"],
    answer:["B"],
    explain:"挑战式销售三要素：教导（Teach）、定制（Tailor）、掌控（Take control）。" },
  { id:"s3a7", chapter:"阶段三 · 会卖", section:"随堂练习", type:"single", dimension:"流程", difficulty:1,
    q:"桑德勒销售法的核心工具是？",
    options:["降价谈判","相互设限（拜访前约定双方条件）","情感营销","饥饿营销"],
    answer:["B"],
    explain:"桑德勒核心工具是「相互设限」：拜访前约定双方条件。" },
  { id:"s3a8", chapter:"阶段三 · 会卖", section:"随堂练习", type:"single", dimension:"流程", difficulty:1,
    q:"RAIN 模式中的 A 指？",
    options:["行动（Action）","注意（Attention）","期望与痛点（Aspirations & Afflictions）","分析（Analysis）"],
    answer:["C"],
    explain:"RAIN = Rapport 关系、Aspirations & Afflictions 期望与痛点、Impact 影响、New reality 新现实；A 是期望与痛点。" },
  { id:"s3a9", chapter:"阶段三 · 会卖", section:"随堂练习", type:"multi", dimension:"表达", difficulty:1,
    q:"价值陈述家族包含哪些方法？（多选）",
    options:["FABE / FAB","NFABE","NFABI","PFABNE","SCQA","SPIN"],
    answer:["A","B","C","D","E"],
    explain:"价值陈述家族：FABE/FAB、NFABE、NFABI、PFABNE、SCQA；SPIN 是提问法，不属价值陈述家族。" },
  { id:"s3a10", chapter:"阶段三 · 会卖", section:"随堂练习", type:"fill", dimension:"表达", difficulty:1,
    q:"FAB 相比 FABE，少掉的环节是______。",
    answer:"证据（E）",
    keywords:["证据","E","e"],
    explain:"FAB = 特征 + 优点 + 利益；FABE 多一个「证据（E）」环节。" },

  /* ================= 阶段三 · 会卖 · 阶段评测 ================= */
  { id:"s3b1", chapter:"阶段三 · 会卖", section:"阶段评测", type:"subjective", dimension:"表达", difficulty:3,
    q:"把功能句「我们支持 20 多种格式上传」改写成完整的 FABE 四层表达。",
    rubric:"① F 特征客观（1 分）；② A 优点相对化（1 分）；③ B 利益落到客户（1 分）；④ E 证据可核验（1 分）；⑤ 每一层都落到客户身上、无「规划中」能力充证据（1 分）。" },
  { id:"s3b2", chapter:"阶段三 · 会卖", section:"阶段评测", type:"single", dimension:"表达", difficulty:2,
    q:"面对技术型客户、且对方要走内部论证流程，讲产品用哪个模型最合适？",
    options:["NFABI","NFABE","AARRR","MEDDIC"],
    answer:["B"],
    explain:"技术型客户 + 内部论证，用 NFABE（以证据收尾）最合适。" },
  { id:"s3b3", chapter:"阶段三 · 会卖", section:"阶段评测", type:"single", dimension:"流程", difficulty:2,
    q:"客户习惯性拖延、反复压价、节奏失控，适用哪种方法？",
    options:["挑战式销售","桑德勒销售法","FABE","AIDA"],
    answer:["B"],
    explain:"拖延压价、节奏失控，用桑德勒「相互设限」掌控节奏。" },
  { id:"s3b4", chapter:"阶段三 · 会卖", section:"阶段评测", type:"single", dimension:"流程", difficulty:2,
    q:"客户自认需求明确、且多家方案同质化，适用哪种方法？",
    options:["顾问式销售","挑战式销售（先给新认知）","SPIN","卡诺模型"],
    answer:["B"],
    explain:"需求明确 + 方案同质化，用挑战式销售先给新认知打破同质。" },
  { id:"s3b5", chapter:"阶段三 · 会卖", section:"阶段评测", type:"subjective", dimension:"流程", difficulty:3,
    q:"针对「客户制度文件分散、一线总在用旧版本」的场景，写出 SPIN 四类提问各一句。",
    rubric:"① 四类问题各一句、顺序正确（S 情景 / P 难点 / I 暗示 / N 需求-回报）（4 分）；② I 类问题必须让客户自己意识到代价（1 分）；③ I 类写成「我们告诉客户代价」扣 1 分。" },
  { id:"s3b6", chapter:"阶段三 · 会卖", section:"阶段评测", type:"judge", dimension:"选择", difficulty:2,
    q:"见到客户就上 FABE 讲卖点，是高效的销售习惯。",
    options:["对","错"],
    answer:["错"],
    explain:"见到客户就上 FABE 是常见误用；应先 SPIN 摸底、确认需求再讲价值。" },
  { id:"s3b7", chapter:"阶段三 · 会卖", section:"阶段评测", type:"single", dimension:"流程", difficulty:2,
    q:"MEDDIC 体检中，商机缺少哪一项时应果断降级？",
    options:["量化指标 M","经济决策人 E","内线支持者 C","以上任缺两项都该先补信息，补不上就止损"],
    answer:["D"],
    explain:"MEDDIC 任缺两项都应先补信息，补不上就止损降级。" },
  { id:"s3b8", chapter:"阶段三 · 会卖", section:"阶段评测", type:"single", dimension:"流程", difficulty:2,
    q:"客户自身需求尚不清晰、需要专业引导，适用哪种方法？",
    options:["挑战式销售","顾问式销售 + RAIN","AARRR","桑德勒"],
    answer:["B"],
    explain:"需求不清晰需专业引导，用顾问式销售 + RAIN。" },
  { id:"s3b9", chapter:"阶段三 · 会卖", section:"阶段评测", type:"subjective", dimension:"表达", difficulty:3,
    q:"写出面向高层客户的 90 秒 3W 开场话术。",
    rubric:"① Why 讲客户痛点而非公司情怀（2 分）；② How 讲知识飞轮机制（1 分）；③ What 收在能力域并留演示钩子（1 分）；④ 篇幅控制在 90 秒内（1 分）。" },
  { id:"s3b10", chapter:"阶段三 · 会卖", section:"阶段评测", type:"judge", dimension:"合规", difficulty:2,
    q:"价值陈述家族的字母展开（如 PFABNE），每位销售可以按自己的理解讲，不必统一。",
    options:["对","错"],
    answer:["错"],
    explain:"字母展开是统一口径，须按标准展开，不可各自发挥。" },

  /* ================= 阶段四 · 会选 · 随堂练习 ================= */
  { id:"s4a1", chapter:"阶段四 · 会选", section:"随堂练习", type:"single", dimension:"选择", difficulty:1,
    q:"「初次接触与摸底」阶段优先用什么方法？",
    options:["FABE、SCQA","SPIN、3W 黄金圈","AARRR","MEDDIC"],
    answer:["B"],
    explain:"初次接触与摸底，用 SPIN、3W 黄金圈。" },
  { id:"s4a2", chapter:"阶段四 · 会选", section:"随堂练习", type:"single", dimension:"选择", difficulty:1,
    q:"「方案陈述」阶段优先用什么方法？",
    options:["NFABE、FABE、SCQA、金字塔原理","SPIN、RAIN","MEDDIC、卡诺","AIDA、4P"],
    answer:["A"],
    explain:"方案陈述阶段用 NFABE、FABE、SCQA、金字塔原理。" },
  { id:"s4a3", chapter:"阶段四 · 会选", section:"随堂练习", type:"single", dimension:"选择", difficulty:1,
    q:"高层决策者时间有限，适合的方法倾向是？",
    options:["NFABI、演示与试用","挑战式销售、3W 黄金圈、SCQA","桑德勒、RAIN","AARRR、4P"],
    answer:["B"],
    explain:"高层时间有限，用挑战式销售、3W 黄金圈、SCQA。" },
  { id:"s4a4", chapter:"阶段四 · 会选", section:"随堂练习", type:"single", dimension:"选择", difficulty:1,
    q:"采购与合规部门的关注点与对应方法是？",
    options:["好不好用 → NFABI","值不值 → 挑战式","合规不合规、有没有依据 → NFABE、金字塔原理","转介绍 → AARRR"],
    answer:["C"],
    explain:"采购与合规部门关注「合规不合规、有没有依据」，用 NFABE、金字塔原理。" },
  { id:"s4a5", chapter:"阶段四 · 会选", section:"随堂练习", type:"judge", dimension:"选择", difficulty:2,
    q:"三张选择表（阶段 / 客户类型 / 决策链角色）孤立使用即可，不用叠加。",
    options:["对","错"],
    answer:["错"],
    explain:"三张表须叠加使用：阶段定主轴，类型与角色收窄，误用清单自查。" },
  { id:"s4a6", chapter:"阶段四 · 会选", section:"随堂练习", type:"single", dimension:"选择", difficulty:1,
    q:"「签约后经营」阶段用什么模型？",
    options:["SPIN","AARRR","FABE","SCQA"],
    answer:["B"],
    explain:"签约后经营用 AARRR 看漏斗，配合 RAIN 深化关系。" },
  { id:"s4a7", chapter:"阶段四 · 会选", section:"随堂练习", type:"single", dimension:"选择", difficulty:2,
    q:"内线支持者最需要你提供什么？",
    options:["现场演示","可转述的结构化材料（金字塔原理）","降价方案","高层拜访"],
    answer:["B"],
    explain:"内线支持者最需要可转述的结构化材料（金字塔原理），帮他向上推动。" },
  { id:"s4a8", chapter:"阶段四 · 会选", section:"随堂练习", type:"multi", dimension:"选择", difficulty:2,
    q:"下列属于「常见误用」的有？（多选）",
    options:["见客户就上 FABE 讲卖点","只讲功能不讲利益","一份材料应对所有客户","背熟模型却填不出内容","按决策链角色拆版本"],
    answer:["A","B","C","D"],
    explain:"「按决策链角色拆版本」是正确做法，不是误用；其余四项均为常见误用。" },

  /* ================= 阶段四 · 会选 · 阶段评测 ================= */
  { id:"s4b1", chapter:"阶段四 · 会选", section:"阶段评测", type:"single", dimension:"选择", difficulty:2,
    q:"一条新线索到手，第一步应该做什么？",
    options:["直接约见演示产品","先用 STP 判断值不值得跟，再用 MEDDIC 决定投入多少资源","立即发报价","找领导拍板"],
    answer:["B"],
    explain:"新线索先用 STP 判断值不值得跟，再用 MEDDIC 决定投入资源。" },
  { id:"s4b2", chapter:"阶段四 · 会选", section:"阶段评测", type:"single", dimension:"选择", difficulty:2,
    q:"「一份材料应对所有客户，谁都不满意」，纠正方法是？",
    options:["把材料做得更长","按决策链角色拆版本","只约高层","发电子版即可"],
    answer:["B"],
    explain:"按决策链角色拆版本，针对性准备材料。" },
  { id:"s4b3", chapter:"阶段四 · 会选", section:"阶段评测", type:"single", dimension:"选择", difficulty:2,
    q:"需求还没确认就讲卖点，纠正方法是？",
    options:["加大声量","先用 SPIN 摸底，再讲价值","换更贵的方案","请客户喝茶"],
    answer:["B"],
    explain:"先 SPIN 摸底、再讲价值——需求未确认时的价值陈述都会失焦。" },
  { id:"s4b4", chapter:"阶段四 · 会选", section:"阶段评测", type:"single", dimension:"选择", difficulty:2,
    q:"「背熟模型却填不出内容」，纠正方法是？",
    options:["多背几遍模型","回到模块一补产品事实课","换一个模型","看竞品话术"],
    answer:["B"],
    explain:"填不出内容是事实底账不牢，应回到模块一补产品事实课。" },
  { id:"s4b5", chapter:"阶段四 · 会选", section:"阶段评测", type:"subjective", dimension:"选择", difficulty:3,
    q:"给出场景：拜访对象是技术评估者、所处阶段是方案陈述。请输出「阶段方法 + 客户类型方法 + 角色方法」的完整组合。",
    rubric:"① 阶段方法：方案陈述 → NFABE/FABE/SCQA/金字塔（1 分）；② 类型方法：技术型客户 → NFABE/SPIN/FABE（1 分）；③ 角色方法：技术评估者 → NFABE、FABE、金字塔原理（1 分）；④ 得出综合组合：NFABE + 金字塔为主（2 分）。" },
  { id:"s4b6", chapter:"阶段四 · 会选", section:"阶段评测", type:"judge", dimension:"选择", difficulty:2,
    q:"对自认需求明确的客户硬推方案，是推进项目的好办法。",
    options:["对","错"],
    answer:["错"],
    explain:"自认需求明确、方案同质化时，应先用挑战式销售给新认知，硬推方案不对。" },
  { id:"s4b7", chapter:"阶段四 · 会选", section:"阶段评测", type:"multi", dimension:"选择", difficulty:2,
    q:"「演示与体验」阶段的优先方法有？（多选）",
    options:["NFABI","FABE","MEDDIC","STP"],
    answer:["A","B"],
    explain:"演示与体验阶段优先 NFABI（冲击体验收尾）、FABE。" },
  { id:"s4b8", chapter:"阶段四 · 会选", section:"阶段评测", type:"single", dimension:"选择", difficulty:2,
    q:"对已有合作客户，正确的经营策略是？",
    options:["重新推销全套功能","用 AARRR 看漏斗、用 RAIN 深化关系，重点在留存与转介绍","降价挽留","减少接触"],
    answer:["B"],
    explain:"已有客户用 AARRR 看漏斗、RAIN 深化关系，重点留存与转介绍。" },

  /* ================= 综合考试卷 · 客观题 ================= */
  { id:"exam1", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"知识", difficulty:1, score:3,
    q:"知识飞轮的第四环是？",
    options:["采集","解析","图谱","应用"],
    answer:["D"],
    explain:"知识飞轮：采集 → 解析 → 图谱 → 应用，第四环是应用。" },
  { id:"exam2", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"知识", difficulty:1, score:3,
    q:"企业空间文件「驳回」时，正确做法是？",
    options:["直接删除文件","记录驳回原因","让上传者自己找问题","搁置不管"],
    answer:["B"],
    explain:"文件驳回时应记录驳回原因，便于上传者整改。" },
  { id:"exam3", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"知识", difficulty:1, score:3,
    q:"相关度 35%–60% 的答案，处理建议是？",
    options:["直接采信","说明知识库覆盖不足，建议补充或细化相关文档","当作无匹配","不用管"],
    answer:["B"],
    explain:"35%–60% 属中等相关度，说明覆盖不足，应建议补充或细化相关文档。" },
  { id:"exam4", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"分析", difficulty:1, score:3,
    q:"STP 中「目标市场选择」用的筛选标准不包括？",
    options:["需求明确","预算存在","决策链可触达","关系远近"],
    answer:["D"],
    explain:"目标市场筛选看需求明确、预算存在、决策链可触达；「关系远近」不是标准。" },
  { id:"exam5", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"分析", difficulty:1, score:3,
    q:"卡诺模型中「做得越好越满意」的是？",
    options:["基本型","期望型","兴奋型","反向型"],
    answer:["B"],
    explain:"期望型需求：做得越好越满意，是线性正相关。" },
  { id:"exam6", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"分析", difficulty:1, score:3,
    q:"SCQA 中 C 代表？",
    options:["结论","冲突","共识","代价"],
    answer:["B"],
    explain:"SCQA = Situation 情境、Conflict 冲突、Question 问题、Answer 答案；C 是冲突。" },
  { id:"exam7", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"表达", difficulty:1, score:3,
    q:"AIDA 模型最后一环是？",
    options:["注意","兴趣","欲望","行动"],
    answer:["D"],
    explain:"AIDA = Attention 注意、Interest 兴趣、Desire 欲望、Action 行动；最后一环是行动。" },
  { id:"exam8", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"流程", difficulty:1, score:3,
    q:"RAIN 模式四步顺序是？",
    options:["关系 → 期望与痛点 → 放大影响 → 新现实","痛点 → 关系 → 新现实 → 影响","影响 → 关系 → 痛点 → 新现实","关系 → 影响 → 痛点 → 新现实"],
    answer:["A"],
    explain:"RAIN = Rapport → Aspirations & Afflictions → Impact → New reality。" },
  { id:"exam9", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"选择", difficulty:1, score:3,
    q:"「商机评估与资源分配」阶段优先方法是？",
    options:["MEDDIC、卡诺模型","FABE、AIDA","SPIN、3W","AARRR、4P"],
    answer:["A"],
    explain:"商机评估与资源分配用 MEDDIC、卡诺模型。" },
  { id:"exam10", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"选择", difficulty:1, score:3,
    q:"使用者（决策链角色）的关注点是？",
    options:["值不值","好不好用、麻不麻烦","合规不合规","能不能嵌入系统"],
    answer:["B"],
    explain:"使用者关注「好不好用、麻不麻烦」；经济决策人关注值不值；技术评估者关注能否嵌入；采购合规关注合规。" },
  { id:"exam11", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"选择", difficulty:1, score:3,
    q:"「竞争性对抗」阶段的优先方法是？",
    options:["挑战式销售、SWOT","AIDA、4P","桑德勒、RAIN","FABE、SPIN"],
    answer:["A"],
    explain:"竞争性对抗阶段用挑战式销售、SWOT。" },
  { id:"exam12", chapter:"综合考试", section:"综合考试卷", type:"single", dimension:"知识", difficulty:1, score:3,
    q:"超级大脑开放平台「空间白名单为空」时的行为是？",
    options:["允许全部空间","直接拒绝（403）","默认开放公共库","需管理员口头授权"],
    answer:["B"],
    explain:"空间白名单为空直接拒绝（403），边界情况不出现「无限制访问」的降级路径。" },
  { id:"exam13", chapter:"综合考试", section:"综合考试卷", type:"multi", dimension:"知识", difficulty:1, score:3,
    q:"下列属于「私有化部署三档硬件配置」的表述？（多选）",
    options:["最低 4 核 8GB/100GB","推荐 8 核 16GB/500GB SSD","企业级 16+ 核 32GB+/2TB+","任意一台办公电脑即可"],
    answer:["A","B","C"],
    explain:"私有化部署三档硬件：最低 4 核 8GB/100GB、推荐 8 核 16GB/500GB SSD、企业级 16+ 核 32GB+/2TB+。" },
  { id:"exam14", chapter:"综合考试", section:"综合考试卷", type:"multi", dimension:"分析", difficulty:1, score:3,
    q:"金字塔原理四条规则包括？（多选）",
    options:["结论先行","以上统下","归类分组","逻辑递进","情感优先"],
    answer:["A","B","C","D"],
    explain:"金字塔原理四条：结论先行、以上统下、归类分组、逻辑递进。" },
  { id:"exam15", chapter:"综合考试", section:"综合考试卷", type:"multi", dimension:"流程", difficulty:1, score:3,
    q:"大客户销售流程组包含的方法有？（多选）",
    options:["挑战式销售","桑德勒销售法","顾问式销售","RAIN 模式","AARRR"],
    answer:["A","B","C","D"],
    explain:"大客户销售流程组：挑战式、桑德勒、顾问式、RAIN；AARRR 属增长运营，不在此组。" },
  { id:"exam16", chapter:"综合考试", section:"综合考试卷", type:"multi", dimension:"合规", difficulty:2, score:3,
    q:"与客户沟通中的合规红线包括？（多选）",
    options:["不承诺「规划中」能力的交付时间","价格口径以商务负责人确认为准，不现场改价","案例统一脱敏口径","为了成交可以口头承诺投产比数字"],
    answer:["A","B","C"],
    explain:"「为成交口头承诺投产比数字」是违规行为，不是红线要求；其余三项是合规红线。" },
  { id:"exam17", chapter:"综合考试", section:"综合考试卷", type:"judge", dimension:"知识", difficulty:1, score:3,
    q:"私有化部署支持气隙（完全离线）环境。",
    options:["对","错"],
    answer:["对"],
    explain:"私有化部署支持气隙（完全离线）环境。" },
  { id:"exam18", chapter:"综合考试", section:"综合考试卷", type:"judge", dimension:"合规", difficulty:2, score:3,
    q:"客户问等保证书，可以回答「我们已取得特定等级保护证书」。",
    options:["对","错"],
    answer:["错"],
    explain:"不能宣称已取得特定等级保护证书；正确口径是按等保标准设计落地、配合客户定级备案测评。" },
  { id:"exam19", chapter:"综合考试", section:"综合考试卷", type:"judge", dimension:"合规", difficulty:2, score:3,
    q:"客户催得急，可以先把投产比按最好案例报出去，事后再补口径。",
    options:["对","错"],
    answer:["错"],
    explain:"投产比数字不得现场口头承诺，必须走商务与财务确认口径；先报后补是违规。" },
  { id:"exam20", chapter:"综合考试", section:"综合考试卷", type:"judge", dimension:"知识", difficulty:1, score:3,
    q:"综合考试后，能力画像只用于培训评估参考，不作为晋升唯一依据。",
    options:["对","错"],
    answer:["对"],
    explain:"能力画像用于培训评估参考，不作为晋升、淘汰的唯一依据。" },

  /* ================= 综合考试卷 · 主观题 ================= */
  { id:"exam21", chapter:"综合考试", section:"综合考试卷", type:"subjective", dimension:"表达", difficulty:3, score:8,
    q:"用不超过 150 字，向客户讲清「超级大脑是什么、对客户的好处、客户需要付出什么」三层内容。",
    rubric:"① 是什么（2 分）；② 好处（直接 + 间接 / 战略，3 分）；③ 付出（金钱、配合事项、组织投入，2 分）；④ 字数与结构（1 分）。出现未标注的具体价格数字：扣 4 分。" },
  { id:"exam22", chapter:"综合考试", section:"综合考试卷", type:"subjective", dimension:"分析", difficulty:3, score:8,
    q:"写出超级大脑 SWOT 中的两个「优势 + 应对思路」组合，并说明对外沟通时劣势该如何处理。",
    rubric:"① 优势与应对思路成对且正确（各 2 分，共 4 分）；② 劣势处理正确：对内复盘用真实表述，对外用中性「相对短板」（2 分）；③ 提到落脚点不在模型能力、在治理深度（2 分）。" },
  { id:"exam23", chapter:"综合考试", section:"综合考试卷", type:"subjective", dimension:"合规", difficulty:3, score:8,
    q:"客户坚持要「价格折扣 + 投产比承诺」才肯推进，请写出你的完整应对流程。",
    rubric:"① 不现场承诺、不现场改价（2 分）；② 明确升级路径：价格 → 商务负责人，投产比 → 商务与财务确认口径（2 分）；③ 用四维测算方法框架替代承诺数字（2 分）；④ 给出可执行的下一步（申请试点 / 反馈时限）（2 分）。" },
  { id:"exam24", chapter:"综合考试", section:"综合考试卷", type:"subjective", dimension:"流程", difficulty:3, score:8,
    q:"情景：你是销售，明天拜访一家城商行的技术评估者，当前阶段是方案陈述。请写出完整拜访设计：开场结构、讲法选择、材料准备、收尾行动。",
    rubric:"① 开场：SCQA 或金字塔结论先行，对准技术评估者「能不能用、稳不稳」（2 分）；② 讲法：NFABE 为主（证据收尾）（2 分）；③ 材料：技术文档 + 安全说明书要点 + 可核查依据（2 分）；④ 收尾：明确行动（试点 / 技术评审材料 / 下次会议）（2 分）。" },
  { id:"exam25", chapter:"综合考试", section:"综合考试卷", type:"subjective", dimension:"合规", difficulty:3, score:8,
    q:"情景：拜访中客户说「你把分利比例和投产比数字写进方案，我今天就立项」。请写出正确处理方式，并说明为什么。",
    rubric:"① 明确拒绝把分利比例与投产比数字写进方案（2 分）；② 说明原因：分利当前商业模式不涉及，投产比口径待商务与财务确认，承诺了就是风险（2 分）；③ 给出替代动作：立项可用试点方案与验收指标替代承诺数字（2 分）；④ 升级给对应责任人并限时反馈（2 分）。出现任何承诺数字：0 分。" },

  /* ================= 业务资料补充题（定稿四部分） ================= */

  /* ---- 阶段一 · 懂产品 · 补充 ---- */
  { id:"s1c1", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:1,
    q:"知识飞轮「采集」环节的关键机制是？",
    options:["20+ 格式统一入口、单文件 ≤100MB、异步解析不阻塞","向量化后入向量库","自动抽取实体与关系","智能问答带引用来源"],
    answer:["A"], explain:"采集环：20+ 格式统一入口、单文件 ≤100MB、异步解析，产出集中入库的企业私有知识源。" },
  { id:"s1c2", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:2,
    q:"知识飞轮「图谱」环节自动抽取的实体、关系与知识晶体数量分别是？",
    options:["6 类实体、12 类关系、8 类晶体","8 类实体、12 类关系、6 类知识晶体","8 类实体、6 类关系、12 类晶体","12 类实体、8 类关系、6 类晶体"],
    answer:["B"], explain:"图谱环自动抽取 8 类实体、12 类关系，沉淀 6 类知识晶体。" },
  { id:"s1c3", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:2,
    q:"超级大脑四层容器化架构中，最底层是？",
    options:["接入层","应用层","引擎层","基础设施层（Docker / MySQL 8 / 向量库 / Redis / 对象存储）"],
    answer:["D"], explain:"四层自下而上：基础设施层 → 引擎层（RAG/向量/图谱推理/Embedding）→ 应用层 → 接入层。" },
  { id:"s1c4", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:1,
    q:"超级大脑前端技术栈是？",
    options:["Next.js + React + Ant Design 6","Vue3 + Element Plus","Angular + Material","纯 jQuery"],
    answer:["A"], explain:"前端 Next.js + React + Ant Design 6；后端 Python FastAPI + SQLAlchemy（REST + SSE 流式）。" },
  { id:"s1c5", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:1,
    q:"新员工上手周期缩短的比例是？",
    options:["30%","50%","70%","90%"],
    answer:["B"], explain:"直接价值：知识检索效率提升 10 倍、新员工上手周期缩短 50%。" },
  { id:"s1c6", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:2,
    q:"SaaS 云端版「标准版」的定价是？",
    options:["¥9.9/人/月","¥19.9/人/月","¥29.9/人/月","¥49.9/人/月"],
    answer:["B"], explain:"SaaS 四档：个人版 ¥9.9、标准版 ¥19.9、专业版 ¥29.9、PRO 版 ¥49.9（人/月）。价格口径以商务负责人为准。" },
  { id:"s1c7", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:2,
    q:"私有化部署「旗舰版」的起步价是？",
    options:["¥60,000/年","¥150,000/年","¥280,000/年","¥500,000/年"],
    answer:["C"], explain:"私有化三档：基础版 ¥6 万/年（100人内单节点）、标准版 ¥15 万/年（500人内集群+高可用）、旗舰版 ¥28 万/年（1000人以上多活+灾备）。" },
  { id:"s1c8", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"multi", dimension:"知识", difficulty:1,
    q:"超级大脑的四种交付模式包括？（多选）",
    options:["SaaS 订阅","私有化部署","OEM 贴牌","ODM 定制","开源免费"],
    answer:["A","B","C","D"], explain:"四种交付模式：SaaS 订阅 / 私有化部署 / OEM 贴牌 / ODM 定制，共用同一能力底座。" },
  { id:"s1c9", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"judge", dimension:"知识", difficulty:1,
    q:"JWT 令牌默认有效期 24 小时，签名密钥由部署方配置、不入代码库。",
    options:["对","错"], answer:["对"],
    explain:"JWT 采用 HS256、默认 24 小时，签名密钥部署时生成强随机值、不入代码库。" },
  { id:"s1c10", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:2,
    q:"知识库级五档访问级别（从高到低）是？",
    options:["owner → manage → edit → use → 无","admin → edit → use → 无","owner → edit → use → view","manage → owner → edit → use"],
    answer:["A"], explain:"五档：owner / manage / edit / use / 无；普通成员对企业公共库为 use（只读）。" },
  { id:"s1c11", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"multi", dimension:"知识", difficulty:2,
    q:"系统自动脱敏的四类个人信息是？（多选）",
    options:["手机号","邮箱","身份证","银行卡","姓名"],
    answer:["A","B","C","D"], explain:"手机号 / 邮箱 / 身份证 / 银行卡四类自动脱敏（纯本地正则），在客服会话入库前与开放平台日志入参落库前两处生效。" },
  { id:"s1c12", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:2,
    q:"知识引擎回答相关度 <35% 时，应如何处理？",
    options:["直接采信","核对原文","建议补充文档","说明无有效匹配"],
    answer:["D"], explain:"相关度分档：≥80% 直接采信、60%–80% 核对原文、35%–60% 建议补文档、<35% 无有效匹配。" },
  { id:"s1c13", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:1,
    q:"上传文件扩展名白名单共有多少种？",
    options:["15 种","20 种","27 种","40 种"],
    answer:["C"], explain:"27 种扩展名白名单，单文件 ≤100MB，查询 ≤2000 字符；类型不在清单内上传即拒绝。" },
  { id:"s1c14", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"multi", dimension:"知识", difficulty:2,
    q:"系统的用户角色包括？（多选）",
    options:["超级管理员 super_admin","企业管理员 admin","普通成员","空间所有者 owner"],
    answer:["A","B","C","D"], explain:"四类角色：super_admin（双端全部权限）、admin（企业端）、普通成员（默认 kb.view）、owner（对自建库等同管理员）。" },
  { id:"s1c15", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"fill", dimension:"知识", difficulty:1,
    q:"知识引擎问答的查询输入最大为____字符。",
    answer:"2000", keywords:["2000"], explain:"查询 ≤2000 字符，超长输入被限制。" },
  { id:"s1c16", chapter:"阶段一 · 懂产品", section:"业务资料补充", type:"single", dimension:"知识", difficulty:2,
    q:"开放平台令牌端点按 IP 的限流阈值是？",
    options:["20 次/分、200 次/时","10 次/分、100 次/时","50 次/分、500 次/时","不限流"],
    answer:["A"], explain:"令牌端点按 IP 20 次/分、200 次/时；按应用 60 次/分、1000 次/时；阈值运营端可调。" },

  /* ---- 阶段二 · 会分析 · 补充 ---- */
  { id:"s2c1", chapter:"阶段二 · 会分析", section:"业务资料补充", type:"single", dimension:"分析", difficulty:2,
    q:"STP 定位陈述要回答的「不同在哪」指的是？",
    options:["相对竞品的差异化定位","价格更低","功能更多","服务更好"],
    answer:["A"], explain:"定位陈述说清「为谁、提供什么、不同在哪」——超级大脑以「数据主权 + 知识结构 + 治理体系」区别于存储型知识库、协作型文档 SaaS、模型原生方案。" },
  { id:"s2c2", chapter:"阶段二 · 会分析", section:"业务资料补充", type:"single", dimension:"分析", difficulty:2,
    q:"三类优先画像的分层运营中，「价值层」对应的是？",
    options:["免费版","SaaS 标准/专业版","私有化标准版","OEM/授权"],
    answer:["C"], explain:"分层运营：引流层（免费版）→ 转化层（SaaS 标准/专业版）→ 价值层（私有化标准版）→ 战略层（旗舰版/ODM）→ 生态层（OEM/授权）。" },
  { id:"s2c3", chapter:"阶段二 · 会分析", section:"业务资料补充", type:"judge", dimension:"分析", difficulty:2,
    q:"4P 匹配检查法要求：任何推广动作都必须有对应的渠道能承接转化。",
    options:["对","错"], answer:["对"],
    explain:"4P 匹配检查三问之一：这次「推广」有没有对应「渠道」承接转化？四 P 必须匹配。" },
  { id:"s2c4", chapter:"阶段二 · 会分析", section:"业务资料补充", type:"single", dimension:"分析", difficulty:2,
    q:"金字塔原理改写示例中，第一句话应该是？",
    options:["罗列功能清单","结论先行——把结论放最前面","先讲细节","先讲背景铺垫"],
    answer:["B"], explain:"金字塔改写先给结论：「超级大脑把企业知识变成 AI 能用、能管、能沉淀的资产」，再分三条支撑。" },
  { id:"s2c5", chapter:"阶段二 · 会分析", section:"业务资料补充", type:"judge", dimension:"分析", difficulty:2,
    q:"SWOT 中，对内复盘用真实劣势（品牌弱、模板少），对外沟通用中性表述「相对短板」。",
    options:["对","错"], answer:["对"],
    explain:"劣势对内真实、对外中性，避免自我否定；落脚点不在模型能力，在治理深度。" },
  { id:"s2c6", chapter:"阶段二 · 会分析", section:"业务资料补充", type:"single", dimension:"分析", difficulty:2,
    q:"3W 黄金圈中，Why 应该讲什么？",
    options:["客户痛点与共识","公司情怀与愿景","产品功能清单","价格优势"],
    answer:["A"], explain:"Why 讲客户痛点（找文档 15 分钟、大模型答案不敢信），不是公司情怀；讲情怀是常见误用。" },
  { id:"s2c7", chapter:"阶段二 · 会分析", section:"业务资料补充", type:"single", dimension:"分析", difficulty:2,
    q:"卡诺模型中，下列哪项属于「期望型」需求？",
    options:["数据不出内网","检索准确率、解析成功率、响应速度","知识图谱可视化","界面装饰"],
    answer:["B"], explain:"检索准确率/解析成功率/响应速度等是「做得越好越满意」的期望型，是日常优化主战场；数据不出内网是基本型，图谱可视化是兴奋型。" },
  { id:"s2c8", chapter:"阶段二 · 会分析", section:"业务资料补充", type:"single", dimension:"分析", difficulty:2,
    q:"卡诺模型中，超级大脑的「数据不出内网（私有化/气隙）」属于？",
    options:["兴奋型","期望型","基本型","反向型"],
    answer:["C"], explain:"数据不出内网、权限合规、答案可追溯、数据不用于训练都是基本型——做不好客户出局，做好了他也认为是「应该的」。" },

  /* ---- 阶段三 · 会卖 · 补充 ---- */
  { id:"s3c1", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"single", dimension:"表达", difficulty:2,
    q:"NFABE 相比 FABE，多出的 N 环节指？",
    options:["需求确认（先提问）","痛点开场","冲击体验","情境共识"],
    answer:["A"], explain:"NFABE 在 FABE 前加 N（需求确认），先提问摸清需求再讲特征利益，最后以证据收尾。" },
  { id:"s3c2", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"single", dimension:"表达", difficulty:2,
    q:"NFABI 的 I 指？",
    options:["证据（Evidence）","冲击（Impact）","兴趣（Interest）","需求（Need）"],
    answer:["B"], explain:"NFABI 末段以 I（冲击/Impact）收尾，通过现场体验与冲击建立信任，属感性说服路径。" },
  { id:"s3c3", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"single", dimension:"表达", difficulty:2,
    q:"PFABNE 的 P 指？",
    options:["痛点（Problem）","价格（Price）","产品（Product）","推广（Promotion）"],
    answer:["A"], explain:"PFABNE 以痛点 P 开场，适用于客户已有痛点但意愿未明的情形——先唤醒痛，再给方案。" },
  { id:"s3c4", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"single", dimension:"表达", difficulty:2,
    q:"SCQA 框架中，S 指？",
    options:["情境（Situation）","冲突（Complication）","问题（Question）","答案（Answer）"],
    answer:["A"], explain:"SCQA = 情境 → 冲突 → 问题 → 答案，S 以共识开场建立信任。" },
  { id:"s3c5", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"judge", dimension:"表达", difficulty:2,
    q:"AIDA 模型是「沟通卡在哪一环」的诊断尺，而非四段式宣讲稿。",
    options:["对","错"], answer:["对"],
    explain:"AIDA 用于诊断沟通卡在注意/兴趣/欲望/行动哪一环，缺哪环补哪环，不是照着讲四段。" },
  { id:"s3c6", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"single", dimension:"流程", difficulty:2,
    q:"挑战式销售 Teach（教导）的要求是？",
    options:["新认知一句话讲完","讲一份完整 PPT","详细介绍产品","列举所有功能"],
    answer:["A"], explain:"Teach 要给一个颠覆认知的洞察，且一句话讲完（知识管理是组织记忆的结构性问题），不是上课讲 PPT。" },
  { id:"s3c7", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"judge", dimension:"流程", difficulty:2,
    q:"桑德勒的「相互设限」是对流程设限，而不是对客户设限。",
    options:["对","错"], answer:["对"],
    explain:"设限是对流程设限（约定试点条件、验收评审），不是「端着」；客户压价也不现场让价。" },
  { id:"s3c8", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"single", dimension:"流程", difficulty:2,
    q:"顾问式销售中，销售的角色转变是？",
    options:["从「推销者」转为「顾问」","从「顾问」转为「推销者」","从「技术」转为「销售」","角色不变"],
    answer:["A"], explain:"顾问式销售以诊断客户问题为起点、与客户共同形成方案，角色从推销者转为顾问。" },
  { id:"s3c9", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"single", dimension:"流程", difficulty:2,
    q:"SPIN 四类提问中，按标准术语修正后的第二类问题是？",
    options:["情景问题","难点问题（Problem）","暗示问题","需求-回报问题"],
    answer:["B"], explain:"SPIN = 情景 → 难点 → 暗示 → 需求-回报；资料修正了原文「问题问题」的笔误为「难点问题」。" },
  { id:"s3c10", chapter:"阶段三 · 会卖", section:"业务资料补充", type:"multi", dimension:"流程", difficulty:2,
    q:"MEDDIC 的六个维度包括？（多选）",
    options:["量化指标 Metrics","经济决策人 Economic buyer","决策标准与决策流程","痛点识别与内线支持者"],
    answer:["A","B","C","D"], explain:"MEDDIC 六维：量化指标、经济决策人、决策标准、决策流程、痛点识别、内线支持者；缺项越多越要止损。" },

  /* ---- 阶段四 · 会选 · 补充 ---- */
  { id:"s4c1", chapter:"阶段四 · 会选", section:"业务资料补充", type:"single", dimension:"选择", difficulty:2,
    q:"9 阶段中「需求确认与诊断」阶段优先用？",
    options:["顾问式销售、RAIN、SPIN","FABE 直接陈述","AARRR","AIDA"],
    answer:["A"], explain:"需求确认与诊断用顾问式销售、RAIN、SPIN，形成客户认同的问题定义。" },
  { id:"s4c2", chapter:"阶段四 · 会选", section:"业务资料补充", type:"single", dimension:"选择", difficulty:2,
    q:"「深化客户关系」阶段优先用？",
    options:["RAIN、桑德勒销售法","SPIN","MEDDIC","STP"],
    answer:["A"], explain:"深化客户关系用 RAIN、桑德勒销售法，推进并掌控节奏。" },
  { id:"s4c3", chapter:"阶段四 · 会选", section:"业务资料补充", type:"single", dimension:"选择", difficulty:2,
    q:"业务型客户（重痛点、重收益）的方法倾向是？",
    options:["PFABNE、AIDA、3W 黄金圈","NFABE、SPIN","挑战式、SCQA","MEDDIC"],
    answer:["A"], explain:"业务型客户重痛点与收益、需场景代入，用 PFABNE、AIDA、3W 黄金圈。" },
  { id:"s4c4", chapter:"阶段四 · 会选", section:"业务资料补充", type:"single", dimension:"选择", difficulty:2,
    q:"经济决策人（决策链角色）的沟通方法是？",
    options:["挑战式销售、SCQA、投产比测算","NFABI 演示","SPIN 提问","AARRR"],
    answer:["A"], explain:"经济决策人关心「值不值、回报多少」，用挑战式销售、SCQA、投产比测算（口径待确认不承诺）。" },
  { id:"s4c5", chapter:"阶段四 · 会选", section:"业务资料补充", type:"single", dimension:"选择", difficulty:2,
    q:"技术评估者（决策链角色）的沟通方法是？",
    options:["NFABE、FABE、金字塔原理","NFABI 演示","AIDA","3W 黄金圈"],
    answer:["A"], explain:"技术评估者关心「能不能用、稳不稳」，用 NFABE、FABE、金字塔原理讲架构与证据。" },
  { id:"s4c6", chapter:"阶段四 · 会选", section:"业务资料补充", type:"multi", dimension:"选择", difficulty:2,
    q:"决策链五类角色包括？（多选）",
    options:["使用者","技术评估者","经济决策人","采购与法务、内线支持者"],
    answer:["A","B","C","D"], explain:"决策链五角色：使用者 / 技术评估者 / 经济决策人 / 采购与法务 / 内线支持者，关注点各不相同。" },
  { id:"s4c7", chapter:"阶段四 · 会选", section:"业务资料补充", type:"judge", dimension:"选择", difficulty:2,
    q:"判断客户类型看「对方用什么语言做决定」——技术型问参数架构，业务型问投入产出。",
    options:["对","错"], answer:["对"],
    explain:"技术型问参数与架构，业务型问投入产出，高层问方向与风险，采购合规问依据与边界。" },
  { id:"s4c8", chapter:"阶段四 · 会选", section:"业务资料补充", type:"judge", dimension:"合规", difficulty:2,
    q:"拜访前 1 分钟自查清单，最后一条是核对「涉及价格、投产比、安全承诺的口径是待确认还是信口承诺」。",
    options:["对","错"], answer:["对"],
    explain:"自查清单五问之一：口径是「待确认」还是信口承诺——这是合规底线。" }
]
});
