/* ============================================================
 * 益寿巴渝 · 题库数据
 * 来源：《益寿巴渝营销培训-课程评测与考试体系（含倾向能力测评）》
 * 六维能力：产品知识/市场分析/价值陈述/需求挖掘/商机评估/增长运营
 * ============================================================ */
window.SYSTEM_DEFS = window.SYSTEM_DEFS || [];
window.SYSTEM_DEFS.push({
  key:'ysby', name:'益寿巴渝', short:'益寿巴渝', icon:'🌿', color:'#16a34a',
  sub:'重庆中老年银发健康服务平台（C 端入口）',
  chapters:['懂产品','会分析','会卖','会选','结业考试'],
  dimensions:['产品知识','市场分析','价值陈述','需求挖掘','商机评估','增长运营','方法选择'],
  exam:{ total:100, duration:120*60, pass:60, title:'结业考试（闭卷 · 100 分 · 120 分钟 · 60 分及格）' },
  bank:[
  /* ============ 阶段一 · 懂产品 ============ */
  {id:'y1',chapter:'懂产品',section:'填空',type:'fill',dimension:'产品知识',difficulty:1,
   q:'益寿巴渝是一款面向____岁以上中老年及其子女决策者的银发健康服务平台，首发市场是____。',
   answer:'50；重庆', keywords:['50','重庆'], explain:'面向 50 岁以上中老年及子女决策者，首发市场重庆。'},
  {id:'y2',chapter:'懂产品',section:'填空',type:'fill',dimension:'产品知识',difficulty:1,
   q:'"一看二积三换"业务主线中，"一看"指____，"三换"指____。',
   answer:'看视频得积分；积分换商品', keywords:['看视频','积分换'], explain:'一看=看视频得积分；三换=积分换商品（快递发货/到店自提）。'},
  {id:'y3',chapter:'懂产品',section:'填空',type:'fill',dimension:'产品知识',difficulty:1,
   q:'益寿巴渝是"益寿城市三极架构"的第____极（C 端入口）。',
   answer:'一', keywords:['一','第1','第一'], explain:'益寿巴渝为 C 端入口，是三极架构第一极。'},
  {id:'y4',chapter:'懂产品',section:'填空',type:'fill',dimension:'产品知识',difficulty:1,
   q:'用户看视频连续播放____秒可获得____积分。',
   answer:'10；10', keywords:['10'], explain:'观看视频连续播放 10 秒得 10 积分。'},
  {id:'y5',chapter:'懂产品',section:'填空',type:'fill',dimension:'产品知识',difficulty:1,
   q:'2025 年全国 60 岁以上人口约____亿，重庆 60 岁以上人口约____万。',
   answer:'3.23；801', keywords:['3.23','801'], explain:'2025 年全国 60+ 约 3.23 亿，重庆约 801 万。'},
  {id:'y6',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'用户在巴渝页看视频，连续播放多久可得积分？',
   options:['3 秒','5 秒','10 秒','60 秒'],
   answer:['C'], explain:'观看 10 秒得 10 积分。'},
  {id:'y7',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'益寿巴渝的商业模式核心是"成本转嫁"，积分成本来自：',
   options:['平台自有资金','B 端药企营销费用','用户付费','政府补贴'],
   answer:['B'], explain:'积分成本来自药企营销费用，非平台自有资金。'},
  {id:'y8',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'中老年用户最缺的三样东西是：',
   options:['钱、时间、流量','被尊重、占便宜、有陪伴','知识、技能、人脉','商品、折扣、物流'],
   answer:['B'], explain:'中老年最缺"被尊重 + 占便宜 + 有陪伴"。'},
  {id:'y9',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'益寿巴渝 APP 的四个主 Tab 是：',
   options:['首页、商城、直播、设置','巴渝、益寿、消息、我的','视频、社交、积分、钱包','推荐、熟人、直播、圈子'],
   answer:['B'], explain:'四个主 Tab：巴渝、益寿、消息、我的。'},
  {id:'y10',chapter:'懂产品',section:'单选',type:'single',dimension:'产品知识',difficulty:1,
   q:'关于积分来源，以下说法正确的是：',
   options:['积分来源有观看视频、每日任务、好友互动三种','当前唯一赚取来源是"观看视频"','积分可以提现','发布动态即得 50 积分'],
   answer:['B'], explain:'当前唯一赚取来源是"观看视频"；积分不提现。'},
  {id:'y11',chapter:'懂产品',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,
   q:'益寿巴渝 PLUS 版支持积分商城兑换商品，履约方式为快递发货或到店自提。',
   options:['对','错'], answer:['对'],
   explain:'积分商城支持纯积分兑换与积分+现金，履约快递发货或到店自提。'},
  {id:'y12',chapter:'懂产品',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,
   q:'益寿巴渝对 C 端用户收费，靠会员费盈利。',
   options:['对','错'], answer:['错'],
   explain:'对 C 端免费，收入来自 B 端药企。'},
  {id:'y13',chapter:'懂产品',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,
   q:'糖豆、美篇、小年糕的案例证明了"银发文娱内容流量 = 收入"。',
   options:['对','错'], answer:['错'],
   explain:'恰恰相反，验证了"内容流量 ≠ 收入"。'},
  {id:'y14',chapter:'懂产品',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,
   q:'产品介绍与系统解决方案的 20 项要素，应按 A→E 五组顺序讲解。',
   options:['对','错'], answer:['对'],
   explain:'20 项要素按 A→E 认知顺序讲解。'},
  {id:'y15',chapter:'懂产品',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,
   q:'报价与结算口径由商务统一对外，销售人员在客户面前不得自行承诺具体数字。',
   options:['对','错'], answer:['对'],
   explain:'报价与结算口径由商务统一对外，不自行承诺。'},
  {id:'y16',chapter:'懂产品',section:'简答',type:'subjective',dimension:'产品知识',difficulty:2,
   q:'请用一句话写出益寿巴渝的市场定位（STP 中的 P）。',
   rubric:'益寿巴渝 = 重庆中老年看健康内容、交同龄朋友、用积分换好物的银发内容与权益平台。'},
  {id:'y17',chapter:'懂产品',section:'简答',type:'subjective',dimension:'产品知识',difficulty:2,
   q:'请列出产品介绍 20 项要素的 A→E 五组名称。',
   rubric:'A 市场与客户认知、B 产品与价值主张、C 商务条款、D 收益与商业闭环、E 试点与规模化。'},

  /* ============ 阶段二 · 会分析 ============ */
  {id:'y18',chapter:'会分析',section:'单选',type:'single',dimension:'市场分析',difficulty:1,
   q:'STP 理论中，益寿巴渝选择的"目标市场"是：',
   options:['全部网民','活力退休族+居家养老族 C 端 + 药企 B 端','仅高龄照护族','仅子女决策者'],
   answer:['B'], explain:'主战场：活力退休族+居家养老族 C 端 + 药企 B 端。'},
  {id:'y19',chapter:'会分析',section:'单选',type:'single',dimension:'市场分析',difficulty:1,
   q:'金字塔原理的核心结构是：',
   options:['先讲细节再讲结论','结论先行、以上统下、归类分组、逻辑递进','由内向外','时间顺序'],
   answer:['B'], explain:'金字塔原理四原则：结论先行、以上统下、归类分组、逻辑递进。'},
  {id:'y20',chapter:'会分析',section:'单选',type:'single',dimension:'市场分析',difficulty:1,
   q:'3W 黄金圈法则的正确表达顺序是：',
   options:['What→How→Why','Why→How→What','How→What→Why','Why→What→How'],
   answer:['B'], explain:'由内向外：Why→How→What。'},
  {id:'y21',chapter:'会分析',section:'单选',type:'single',dimension:'市场分析',difficulty:1,
   q:'卡诺模型中，"基本型需求"的特征是：',
   options:['做好了会加分','做不好会被淘汰，做好了也不会加分','越多越好','带来惊喜'],
   answer:['B'], explain:'基本型做不好被淘汰，做好不加分。'},
  {id:'y22',chapter:'会分析',section:'单选',type:'single',dimension:'市场分析',difficulty:1,
   q:'SWOT 分析中，"机会"和"威胁"分析的是：',
   options:['内部因素','外部因素','竞争对手内部','财务数据'],
   answer:['B'], explain:'机会/威胁分析外部因素；优势/劣势分析内部。'},
  {id:'y23',chapter:'会分析',section:'判断',type:'judge',dimension:'市场分析',difficulty:1,
   q:'4P 营销理论中，只动一个 P 而其他 P 不配套，营销动作仍能有效。',
   options:['对','错'], answer:['错'],
   explain:'4P 必须互相匹配，不可单点发力。'},
  {id:'y24',chapter:'会分析',section:'判断',type:'judge',dimension:'市场分析',difficulty:1,
   q:'SWOT 分析只需要把四个格子填满就算完成任务。',
   options:['对','错'], answer:['错'],
   explain:'要得出行动结论，不是只填格子。'},
  {id:'y25',chapter:'会分析',section:'判断',type:'judge',dimension:'市场分析',difficulty:1,
   q:'3W 黄金圈与常规"先说产品功能"的顺序相反。',
   options:['对','错'], answer:['对'],
   explain:'黄金圈与常规顺序相反，由内向外先讲 Why。'},
  {id:'y26',chapter:'会分析',section:'判断',type:'judge',dimension:'市场分析',difficulty:1,
   q:'卡诺模型中"兴奋型需求"才是差异化的来源。',
   options:['对','错'], answer:['对'],
   explain:'兴奋型是差异化来源。'},
  {id:'y27',chapter:'会分析',section:'情景应用',type:'subjective',dimension:'市场分析',difficulty:2,
   q:'你要向药企董事长做 90 秒开场介绍，应该用什么方法？请写出前三句。',
   rubric:'用 3W 黄金圈。示例：①中国 3.23 亿老人、重庆 801 万，退休后最缺的不是钱，是"被尊重、占便宜、有陪伴"（Why）；②我们用"看健康内容赚积分、积分换好物"把时间变实惠（How）；③所以做了益寿巴渝这个平台（What）。'},
  {id:'y28',chapter:'会分析',section:'情景应用',type:'subjective',dimension:'市场分析',difficulty:2,
   q:'团队要推广"积分商城上新"这个动作，请用 4P 框架检查：还需要配套什么？',
   rubric:'产品=积分商城上新；价格=积分/积分+现金；渠道=APP商城入口+快递发货/到店自提；推广=社群通知+活动报名+直播弹幕+现场演示。重点：推广拉新必须与产品兑换品类、渠道履约方式配套。'},
  {id:'y29',chapter:'会分析',section:'情景应用',type:'subjective',dimension:'价值陈述',difficulty:2,
   q:'用金字塔原理，把"益寿巴渝有视频、有积分、有社交、有直播"这段平铺罗列，改写成结论先行的表达。',
   rubric:'结论先行示例："益寿巴渝解决银发人群两大痛点——内容供给错配（双列内容瀑布流+智能审核）与社交孤立（即时通讯+圈子+直播弹幕）。"先结论，再分组支撑。'},

  /* ============ 阶段三 · 会卖 ============ */
  {id:'y30',chapter:'会卖',section:'单选',type:'single',dimension:'价值陈述',difficulty:1,
   q:'FABE 法则中，F、A、B、E 分别指：',
   options:['功能、优点、利益、证据','特征、优点、利益、证据','特征、行动、利益、体验','事实、分析、背景、评价'],
   answer:['B'], explain:'F 特征、A 优点、B 利益、E 证据。'},
  {id:'y31',chapter:'会卖',section:'单选',type:'single',dimension:'价值陈述',difficulty:1,
   q:'强调"先确认客户需求、再讲特征利益、以证据收尾"的模型是：',
   options:['FABE','NFABE','NFABI','PFABNE'],
   answer:['B'], explain:'NFABE 在前加 N（需求确认）。'},
  {id:'y32',chapter:'会卖',section:'单选',type:'single',dimension:'需求挖掘',difficulty:1,
   q:'SPIN 提问法中，关键在第三类问题（暗示问题），其作用是：',
   options:['了解客户现状','让客户自己意识到问题的代价','给客户答案','确认预算'],
   answer:['B'], explain:'暗示问题让客户自己意识到代价。'},
  {id:'y33',chapter:'会卖',section:'单选',type:'single',dimension:'商机评估',difficulty:1,
   q:'MEDDIC 中，"Economic buyer"指：',
   options:['使用者','技术评估者','经济决策人','内线支持者'],
   answer:['C'], explain:'Economic buyer = 经济决策人。'},
  {id:'y34',chapter:'会卖',section:'单选',type:'single',dimension:'价值陈述',difficulty:1,
   q:'挑战式销售的核心是"三 T"，指：',
   options:['教导、定制、掌控','谈话、谈判、推进','特征、优点、利益','关系、期望、影响'],
   answer:['A'], explain:'三 T：教导 Teach、定制 Tailor、掌控 Take Control。'},
  {id:'y35',chapter:'会卖',section:'情景匹配',type:'single',dimension:'价值陈述',difficulty:2,
   q:'客户自认需求明确，但方案同质化严重，需要给客户新认知。应选：',
   options:['挑战式销售','桑德勒销售法','顾问式销售','RAIN 模式'],
   answer:['A'], explain:'挑战式销售给新认知。'},
  {id:'y36',chapter:'会卖',section:'情景匹配',type:'single',dimension:'价值陈述',difficulty:2,
   q:'客户习惯性拖延、比价压价，需要建立对等关系、设定资格条件。应选：',
   options:['挑战式销售','桑德勒销售法','顾问式销售','RAIN 模式'],
   answer:['B'], explain:'桑德勒相互设限、平等关系。'},
  {id:'y37',chapter:'会卖',section:'情景匹配',type:'single',dimension:'需求挖掘',difficulty:2,
   q:'客户自身需求尚不清晰，需要专业引导、共同诊断。应选：',
   options:['挑战式销售','桑德勒销售法','顾问式销售','RAIN 模式'],
   answer:['C'], explain:'顾问式诊断引导。'},
  {id:'y38',chapter:'会卖',section:'情景匹配',type:'single',dimension:'增长运营',difficulty:2,
   q:'长周期大客户培育，需求从无到有，需要建立关系、放大影响、描绘新现实。应选：',
   options:['挑战式销售','桑德勒销售法','顾问式销售','RAIN 模式'],
   answer:['D'], explain:'RAIN 建立关系、放大影响。'},
  {id:'y39',chapter:'会卖',section:'话术设计',type:'subjective',dimension:'需求挖掘',difficulty:3,
   q:'用 SPIN 提问法，为药企客户设计四连问（情景/问题/暗示/需求回报）。',
   rubric:'S 情景："你们营销费用主要投哪些渠道？"；P 问题："带金销售是不是越来越难走？"；I 暗示："继续投传统渠道，被纠风处罚的风险有多大？"；N 需求回报："合规载体既触达精准老年人群又沉淀数据资产，对你们意味着什么？"'},
  {id:'y40',chapter:'会卖',section:'话术设计',type:'subjective',dimension:'价值陈述',difficulty:3,
   q:'用 FABE 法则，把"益寿巴渝看视频得积分"这个功能写成一段完整的话术。',
   rubric:'F=看视频得积分（观看10秒得10积分）；A=碎片时间攒积分、门槛低；B=对药企获得合规内容触达和精准中老年曝光；E=中老年是微短剧付费主力，药企 3291 亿营销费用正在寻找合规出口。'},

  /* ============ 阶段四 · 会选 ============ */
  {id:'y41',chapter:'会选',section:'情景选择',type:'single',dimension:'方法选择',difficulty:2,
   q:'第一次见一个新药企客户、需求不明，你应该：',
   options:['直接上 FABE 讲卖点','先用 SPIN + 3W 摸底','直接报价','先演示产品'],
   answer:['B'], explain:'先用 SPIN 摸底，再讲价值。'},
  {id:'y42',chapter:'会选',section:'情景选择',type:'single',dimension:'方法选择',difficulty:2,
   q:'面对药企的法务/合规部门，最该用：',
   options:['挑战式销售','NFABI 演示','NFABE + 金字塔原理（结构化可核查材料）','AARRR'],
   answer:['C'], explain:'采购合规部门要结构化材料与可核查依据。'},
  {id:'y43',chapter:'会选',section:'情景选择',type:'single',dimension:'方法选择',difficulty:2,
   q:'面对药企董事长（时间有限），最该用：',
   options:['顾问式销售','挑战式销售 + SCQA（结论先行、给新认知）','桑德勒','AIDA'],
   answer:['B'], explain:'高层时间有限，需新认知与结论先行。'},
  {id:'y44',chapter:'会选',section:'情景选择',type:'single',dimension:'方法选择',difficulty:2,
   q:'面对最终使用者（中老年），最该用：',
   options:['NFABE','NFABI + 演示试用','MEDDIC','SPIN'],
   answer:['B'], explain:'使用者关注好不好用，NFABI 演示试用。'},
  {id:'y45',chapter:'会选',section:'情景选择',type:'single',dimension:'方法选择',difficulty:2,
   q:'客户说"我们就是要投广告、要曝光量"（自认需求明确），你该：',
   options:['迎合他直接推广告方案','用挑战式销售给新认知','直接降价','放弃'],
   answer:['B'], explain:'挑战式销售给新认知："你们要的不是曝光，是合规精准触达"。'},
  {id:'y46',chapter:'会选',section:'纠错',type:'subjective',dimension:'方法选择',difficulty:2,
   q:'纠错：指出"见客户就上 FABE 讲卖点"的错误，并给出纠正。',
   rubric:'错误：需求未确认，讲了白讲。纠正：先用 SPIN 摸底再讲价值。'},
  {id:'y47',chapter:'会选',section:'纠错',type:'subjective',dimension:'方法选择',difficulty:2,
   q:'纠错：指出"只讲功能不讲利益"的错误，并给出纠正。',
   rubric:'错误：客户不知道跟自己有什么关系。纠正：每一层都落到客户利益。'},
  {id:'y48',chapter:'会选',section:'纠错',type:'subjective',dimension:'方法选择',difficulty:2,
   q:'纠错：指出"一份材料应对所有客户"的错误，并给出纠正。',
   rubric:'错误：各角色关注点不同。纠正：按决策链角色拆版本。'},
  {id:'y49',chapter:'会选',section:'纠错',type:'subjective',dimension:'方法选择',difficulty:2,
   q:'纠错：指出"背熟模型却填不出内容"的错误，并给出纠正。',
   rubric:'错误：产品事实没掌握。纠正：回模块一补课。'},
  {id:'y50',chapter:'会选',section:'纠错',type:'subjective',dimension:'方法选择',difficulty:2,
   q:'纠错：指出"对自认需求明确的客户硬推"的错误，并给出纠正。',
   rubric:'错误：引起对抗。纠正：改用挑战式销售，先给新认知。'},

  /* ============ 结业考试 ============ */
  {id:'ye1',chapter:'结业考试',section:'单选',type:'single',dimension:'产品知识',difficulty:1,score:2,
   q:'益寿巴渝补贴资金的来源是：',
   options:['平台自有资金','B 端药企营销费用','用户付费','广告收入'],
   answer:['B'], explain:'积分成本来自 B 端药企营销费用。'},
  {id:'ye2',chapter:'结业考试',section:'单选',type:'single',dimension:'产品知识',difficulty:1,score:2,
   q:'积分商城的商品有哪几种履约方式？',
   options:['仅快递发货','仅到店自提','快递发货或到店自提','仅线下自取且需扫码'],
   answer:['C'], explain:'快递发货或到店自提。'},
  {id:'ye3',chapter:'结业考试',section:'单选',type:'single',dimension:'市场分析',difficulty:1,score:2,
   q:'STP 的 P 指：',
   options:['Product','Price','Positioning','Promotion'],
   answer:['C'], explain:'P = Positioning 定位。'},
  {id:'ye4',chapter:'结业考试',section:'单选',type:'single',dimension:'市场分析',difficulty:1,score:2,
   q:'金字塔原理的第一原则是：',
   options:['归类分组','结论先行','逻辑递进','以上统下'],
   answer:['B'], explain:'第一原则是结论先行。'},
  {id:'ye5',chapter:'结业考试',section:'单选',type:'single',dimension:'需求挖掘',difficulty:1,score:2,
   q:'SPIN 的关键在：',
   options:['情景问题','问题问题','暗示问题','需求回报问题'],
   answer:['C'], explain:'关键在暗示问题。'},
  {id:'ye6',chapter:'结业考试',section:'单选',type:'single',dimension:'需求挖掘',difficulty:1,score:2,
   q:'"让客户自己意识到问题的代价"靠的是：',
   options:['情景问题','暗示问题','需求回报问题','直接陈述'],
   answer:['B'], explain:'暗示问题让客户意识到代价。'},
  {id:'ye7',chapter:'结业考试',section:'单选',type:'single',dimension:'商机评估',difficulty:1,score:2,
   q:'MEDDIC 的 M 指：',
   options:['市场','量化指标（Metrics）','营销','会员'],
   answer:['B'], explain:'M = Metrics 量化指标。'},
  {id:'ye8',chapter:'结业考试',section:'单选',type:'single',dimension:'增长运营',difficulty:1,score:2,
   q:'AARRR 五级漏斗的最后一级是：',
   options:['收入','留存','推荐','激活'],
   answer:['C'], explain:'最后一级是推荐 Referral。'},
  {id:'ye9',chapter:'结业考试',section:'单选',type:'single',dimension:'价值陈述',difficulty:1,score:2,
   q:'面对技术型客户，最该用：',
   options:['NFABE + SPIN','NFABI','AIDA','3W'],
   answer:['A'], explain:'技术型客户用 NFABE + SPIN。'},
  {id:'ye10',chapter:'结业考试',section:'单选',type:'single',dimension:'增长运营',difficulty:1,score:2,
   q:'益寿巴渝当前最需要加强的环节是：',
   options:['获客','激活','收入','推荐（圈层口碑与活动传播）'],
   answer:['D'], explain:'最需加强推荐（圈层口碑与活动传播）。'},
  {id:'ye11',chapter:'结业考试',section:'多选',type:'multi',dimension:'产品知识',difficulty:1,score:3,
   q:'以下属于益寿巴渝"已上线"能力的是：',
   options:['看视频得积分','积分商城兑换商品','即时通讯（野火 IM）','直播与弹幕互动'],
   answer:['A','B','C','D'], explain:'四项均已上线。'},
  {id:'ye12',chapter:'结业考试',section:'多选',type:'multi',dimension:'价值陈述',difficulty:1,score:3,
   q:'属于"价值陈述家族"的方法有：',
   options:['FABE','NFABE','SCQA','SPIN'],
   answer:['A','B','C'], explain:'SPIN 是提问法，不属价值陈述家族。'},
  {id:'ye13',chapter:'结业考试',section:'多选',type:'multi',dimension:'价值陈述',difficulty:1,score:3,
   q:'属于"大客户销售流程"的方法有：',
   options:['挑战式销售','桑德勒销售法','顾问式销售','RAIN 模式'],
   answer:['A','B','C','D'], explain:'四项均属大客户销售流程。'},
  {id:'ye14',chapter:'结业考试',section:'多选',type:'multi',dimension:'市场分析',difficulty:1,score:3,
   q:'卡诺模型的需求类型包括：',
   options:['基本型','期望型','兴奋型','反向型'],
   answer:['A','B','C','D'], explain:'卡诺模型含基本/期望/兴奋/无差异/反向型（题给四项均属）。'},
  {id:'ye15',chapter:'结业考试',section:'多选',type:'multi',dimension:'产品知识',difficulty:1,score:3,
   q:'益寿巴渝解决的两大痛点是：',
   options:['内容供给错配','社交孤立','商品供给不足','资金链断裂'],
   answer:['A','B'], explain:'两大痛点：内容供给错配、社交孤立。'},
  {id:'ye16',chapter:'结业考试',section:'判断',type:'judge',dimension:'增长运营',difficulty:1,score:1,
   q:'积分是拉新钩子，也是留存本身。',
   options:['对','错'], answer:['错'],
   explain:'积分是钩子，不是留存本身。'},
  {id:'ye17',chapter:'结业考试',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,score:1,
   q:'积分成本来自 B 端药企营销费用时，每一分积分背后都有真实的 B 端预算对应。',
   options:['对','错'], answer:['对'],
   explain:'积分成本来自药企营销费用，有真实预算对应。'},
  {id:'ye18',chapter:'结业考试',section:'判断',type:'judge',dimension:'市场分析',difficulty:1,score:1,
   q:'3W 黄金圈应由内向外表达。',
   options:['对','错'], answer:['对'],
   explain:'黄金圈由内向外。'},
  {id:'ye19',chapter:'结业考试',section:'判断',type:'judge',dimension:'价值陈述',difficulty:1,score:1,
   q:'挑战式销售的核心是"教导、定制、掌控"。',
   options:['对','错'], answer:['对'],
   explain:'挑战式销售核心三 T。'},
  {id:'ye20',chapter:'结业考试',section:'判断',type:'judge',dimension:'价值陈述',difficulty:1,score:1,
   q:'顾问式销售中，销售角色是"推销者"。',
   options:['对','错'], answer:['错'],
   explain:'顾问式销售中销售是顾问，非推销者。'},
  {id:'ye21',chapter:'结业考试',section:'判断',type:'judge',dimension:'商机评估',difficulty:1,score:1,
   q:'MEDDIC 中 Champion 指内线支持者。',
   options:['对','错'], answer:['对'],
   explain:'Champion = 内线支持者。'},
  {id:'ye22',chapter:'结业考试',section:'判断',type:'judge',dimension:'方法选择',difficulty:1,score:1,
   q:'对 C 端中老年用户，应该多用专业术语体现专业度。',
   options:['对','错'], answer:['错'],
   explain:'应用生活化语言，非专业术语。'},
  {id:'ye23',chapter:'结业考试',section:'判断',type:'judge',dimension:'方法选择',difficulty:1,score:1,
   q:'一份材料可以应对所有客户。',
   options:['对','错'], answer:['错'],
   explain:'应按决策链角色拆版本。'},
  {id:'ye24',chapter:'结业考试',section:'判断',type:'judge',dimension:'增长运营',difficulty:1,score:1,
   q:'AARRR 关注的是逐级转化率而非单点流量。',
   options:['对','错'], answer:['对'],
   explain:'AARRR 关注逐级转化率。'},
  {id:'ye25',chapter:'结业考试',section:'判断',type:'judge',dimension:'产品知识',difficulty:1,score:1,
   q:'报价与结算口径由商务统一对外，销售人员不得凭估计向客户承诺具体数字。',
   options:['对','错'], answer:['对'],
   explain:'口径由商务统一对外。'},
  {id:'ye26',chapter:'结业考试',section:'简答',type:'subjective',dimension:'产品知识',difficulty:2,score:5,
   q:'请简述"一看二积三换"的完整含义（三换包含积分商城兑换与快递发货/到店自提两种履约方式）。',
   rubric:'一看=看视频得积分（视频连续播放10秒得10积分）；二积=积分体系与积分账本（唯一赚取来源为观看视频）；三换=积分商城兑换商品，支持纯积分兑换与积分+现金混合支付，履约方式为快递发货或到店自提。漏一项扣1分。'},
  {id:'ye27',chapter:'结业考试',section:'简答',type:'subjective',dimension:'产品知识',difficulty:2,score:5,
   q:'请说明"成本转嫁"机制与"趣头条式纯网赚"的本质区别（至少两点）。',
   rubric:'①补贴资金来源不同（B端营销费用 vs 平台自有资金）；②平台会计角色不同（中介 vs 成本中心）；③补贴停止后后果不同（有内容服务关系承接 vs 用户立即流失）。答对两点得满分。'},
  {id:'ye28',chapter:'结业考试',section:'简答',type:'subjective',dimension:'需求挖掘',difficulty:2,score:5,
   q:'请写出 SPIN 四类提问的名称，并各举一个对药企客户的问句。',
   rubric:'情景/问题/暗示/需求回报，各举一例，每个1分+名称1分。'},
  {id:'ye29',chapter:'结业考试',section:'简答',type:'subjective',dimension:'方法选择',difficulty:2,score:5,
   q:'请列出"按决策链角色选择方法"的对照关系（至少三个角色）。',
   rubric:'使用者→NFABI/演示；技术评估者→NFABE/金字塔；经济决策人→挑战式/SCQA/投产比；采购法务→NFABE/安全说明；内线支持者→金字塔/结构化材料。答对三个及以上得满分。'},
  {id:'ye30',chapter:'结业考试',section:'案例分析',type:'subjective',dimension:'需求挖掘',difficulty:3,score:15,
   q:'案例：连锁健康商品零售机构老板（业务型，重收益）说"我有 5 家门店，想找平台帮我触达周边中老年客群，你报个价吧"。问题：①先用什么方法、为什么；②用顾问式或 SPIN 写前三个提问；③结合 PLUS 版"不承载线下服务履约、商品可到店自提"能力边界，如何回应"引流到店"诉求。',
   rubric:'(1)先用顾问式销售/SPIN摸底，需求未明确不能上来报价（5分）；(2)参考SPIN三问（5分）；(3)如实说明能力边界："平台不承载线下服务履约，无法承诺引流到店闭环；但积分商城支持到店自提，可先以内容触达+积分权益+到店自提方式合作"（5分）。'},
  {id:'ye31',chapter:'结业考试',section:'案例分析',type:'subjective',dimension:'方法选择',difficulty:3,score:15,
   q:'案例：向药企首次方案汇报，现场有市场总监（业务型）和法务合规负责人（技术/合规型）两人。问题：①汇报开场用什么方法；②两位关注点不同，材料如何准备；③市场总监说"你们和别的广告渠道没区别"，用什么方法应对。',
   rubric:'(1)SCQA或3W开场（5分）；(2)按角色拆版本：市场总监讲痛点收益，合规负责人讲结构化可核查材料（5分）；(3)挑战式销售给新认知："你们要的不是曝光，是合规的精准触达"（5分）。'},
  {id:'ye32',chapter:'结业考试',section:'综合应用',type:'subjective',dimension:'方法选择',difficulty:3,score:5,
   q:'请为益寿巴渝设计一个完整的"新药企客户"销售流程，用方法名称串联，并说明每个环节用什么方法、解决什么问题。',
   rubric:'示例：STP/SWOT筛选商机→SPIN摸底需求→顾问式/RAIN诊断→NFABE/SCQA陈述方案→NFABI演示→MEDDIC评估→挑战式对抗异议→AARRR签约后经营。方法串联合理、每环节说明清楚得满分。'}
  ]
});
